/**
 * ml-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { outboxSchema } from "./outbox.js";
import { schema as modelsSchema } from "../modules/models/schema.js";
import { schema as predictionsSchema } from "../modules/predictions/schema.js";
import { schema as featureStoreSchema } from "../modules/feature-store/schema.js";
import { schema as trainingSchema } from "../modules/training/schema.js";

const SCHEMA = {
  ...outboxSchema,
  ...modelsSchema,
  ...predictionsSchema,
  ...featureStoreSchema,
  ...trainingSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
