/**
 * asset-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as registerModule }     from "../modules/register/schema.js";
import { schema as lifecycleModule }    from "../modules/lifecycle/schema.js";
import { schema as depModule }          from "../modules/depreciation/schema.js";
import { schema as maintenanceModule }  from "../modules/maintenance/schema.js";
import { schema as insuranceModule }    from "../modules/insurance/schema.js";
import { schema as verificationModule } from "../modules/verification/schema.js";
import { outboxSchema }                 from "./outbox.js";

const SCHEMA = {
  ...registerModule,
  ...lifecycleModule,
  ...depModule,
  ...maintenanceModule,
  ...insuranceModule,
  ...verificationModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
