/**
 * asset-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as registerModule }     from "../modules/register/schema.js";
import { schema as lifecycleModule }    from "../modules/lifecycle/schema.js";
import { schema as depModule }          from "../modules/depreciation/schema.js";
import { schema as maintenanceModule }  from "../modules/maintenance/schema.js";
import { schema as insuranceModule }    from "../modules/insurance/schema.js";
import { schema as verificationModule } from "../modules/verification/schema.js";
import { outboxSchema }                 from "./outbox.js";

const SCHEMA = {
  ...registerModule,
  ...lifecycleModule,
  ...depModule,
  ...maintenanceModule,
  ...insuranceModule,
  ...verificationModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes createTenantDb's
 * `wrapWithTenantGuc`-wrapped `db` set the GUC from AsyncLocalStorage -- reads
 * are then correctly tenant-scoped by RLS, not merely by an app-layer WHERE.
 * Mirrors court-service / visitor-service / meeting-service / hrms-service /
 * payroll-service / workflow-service.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => PromiseLike<T>): Promise<T> {
  return db.transaction(fn as (tx: ScopedTx) => Promise<T>);
}
