/**
 * inventory-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as itemsModule } from "../modules/items/schema.js";
import { schema as storesModule } from "../modules/stores/schema.js";
import { schema as movementsModule } from "../modules/movements/schema.js";
import { schema as batchesModule } from "../modules/batches/schema.js";
import { schema as cycleCountModule } from "../modules/cycle-count/schema.js";
import { schema as matchingModule } from "../modules/matching/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...itemsModule,
  ...storesModule,
  ...movementsModule,
  ...batchesModule,
  ...cycleCountModule,
  ...matchingModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
