/**
 * finance-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as budgetModule }   from "../modules/budget/schema.js";
import { schema as glModule }       from "../modules/gl/schema.js";
import { schema as treasuryModule } from "../modules/treasury/schema.js";
import { schema as paymentsModule } from "../modules/payments/schema.js";
import { schema as auditModule }    from "../modules/audit/schema.js";
import { schema as periodCloseModule } from "../modules/period-close/schema.js";
import { schema as hoaModule }      from "../modules/hoa/schema.js";
import { schema as mastersModule }  from "../modules/masters/schema.js";
import { schema as bankReconModule } from "../modules/bank-recon/schema.js";
import { schema as simplifiedModule } from "../modules/simplified/schema.js";
import { schema as anomalyModule }    from "../modules/anomaly/schema.js";
import { allocationSchema } from "../modules/budget/allocation-schema.js";
import { outboxSchema }             from "./outbox.js";

const SCHEMA = {
  ...budgetModule,
  ...glModule,
  ...treasuryModule,
  ...paymentsModule,
  ...auditModule,
  ...periodCloseModule,
  ...hoaModule,
  ...mastersModule,
  ...bankReconModule,
  ...simplifiedModule,
  ...anomalyModule,
  ...allocationSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
