/**
 * finance-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as budgetModule }   from "../modules/budget/schema.js";
import { schema as glModule }       from "../modules/gl/schema.js";
import { schema as treasuryModule } from "../modules/treasury/schema.js";
import { schema as paymentsModule } from "../modules/payments/schema.js";
import { schema as auditModule }    from "../modules/audit/schema.js";
import { schema as periodCloseModule } from "../modules/period-close/schema.js";
import { schema as hoaModule }      from "../modules/hoa/schema.js";
import { schema as mastersModule }  from "../modules/masters/schema.js";
import { schema as bankReconModule } from "../modules/bank-recon/schema.js";
import { schema as simplifiedModule } from "../modules/simplified/schema.js";
import { schema as anomalyModule }    from "../modules/anomaly/schema.js";
import { allocationSchema } from "../modules/budget/allocation-schema.js";
import { outcomeSchema } from "../modules/budget/outcome-schema.js";
import { formulationSchema } from "../modules/budget/formulation-schema.js";
import { schema as resolutionIntakeModule } from "../modules/resolution-intake/schema.js";
import { outboxSchema }             from "./outbox.js";

const SCHEMA = {
  ...budgetModule,
  ...glModule,
  ...treasuryModule,
  ...paymentsModule,
  ...auditModule,
  ...periodCloseModule,
  ...hoaModule,
  ...mastersModule,
  ...bankReconModule,
  ...simplifiedModule,
  ...anomalyModule,
  ...allocationSchema,
  ...outcomeSchema,
  ...formulationSchema,
  ...resolutionIntakeModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain db.select()/db.execute() runs on a pooled connection
 * with no app.tenant_id GUC set, so under the NOBYPASSRLS finance_svc role the
 * fail-closed policy returns ZERO rows. Wrapping the read in db.transaction lets
 * createTenantDb's `wrapWithTenantGuc`-wrapped `db` set the GUC from
 * AsyncLocalStorage, so reads are tenant-scoped by RLS, not merely by an
 * app-layer WHERE. Preserved across the TenantRouter-adoption codemod so
 * existing call sites keep importing this helper unchanged.
 */
export function scopedRead<T>(fn: (tx: Db) => PromiseLike<T>): Promise<T> {
  // tx is typed as the full db surface so drizzle row types are preserved at
  // call sites (no per-call type args needed); the runtime tx is the pg
  // transaction, which exposes the same select/execute methods.
  return db.transaction(fn as unknown as (tx: any) => Promise<T>);
}
