import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { resolveContext, requireRole, HttpError } from "../../shared/context.js";
import { buildForm16, parseFy } from "../tax/form16.js";
import { HrmsUnavailableError } from "../../shared/hrms-client.js";

const READER_ROLES = ["payroll_admin", "payroll_officer", "super_admin", "hr_admin", "finance_officer", "employee"];

const inr = (n: number) => n.toLocaleString("en-IN", { minimumFractionDigits: 2 });

function renderForm16(f: Awaited<ReturnType<typeof buildForm16>>): string {
  const a = f.form16PartA, b = f.form16PartB;
  const row = (label: string, val: number, bold = false) =>
    `<tr><td>${bold ? `<strong>${label}</strong>` : label}</td><td class="amount">${bold ? `<strong>₹ ${inr(val)}</strong>` : `₹ ${inr(val)}`}</td></tr>`;
  return `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><title>Form 16 — FY ${f.fy}</title>
<style>
body{font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:24px;font-size:13px}
h1{text-align:center;font-size:16px} h2{font-size:14px;margin-top:20px}
table{width:100%;border-collapse:collapse;margin:8px 0}
th,td{border:1px solid #333;padding:6px 8px} .amount{text-align:right}
.meta td{border:none;padding:2px 8px}
</style></head><body>
<h1>Form 16 — Certificate under Section 203 of the Income-tax Act, 1961</h1>
<table class="meta">
<tr><td><strong>Financial Year:</strong> ${f.fy}</td><td><strong>Assessment Year:</strong> ${f.assessmentYear}</td></tr>
</table>
<h2>Part A — Deductor &amp; Deductee, TDS Deposited</h2>
<table>
<tr><td>Deductor (Employer)</td><td>${a.deductor.name}</td></tr>
<tr><td>Deductor TAN</td><td>${a.deductor.tan}</td></tr>
<tr><td>Deductor PAN</td><td>${a.deductor.pan}</td></tr>
<tr><td>Employee (Deductee)</td><td>${a.deductee.name || f.employeeId}</td></tr>
<tr><td>Employee PAN</td><td>${a.deductee.pan || "—"}</td></tr>
</table>
<table>
<tr><th>Quarter</th><th class="amount">TDS Deposited</th></tr>
<tr><td>Q1 (Apr–Jun)</td><td class="amount">₹ ${inr(a.quarterlyTds.Q1)}</td></tr>
<tr><td>Q2 (Jul–Sep)</td><td class="amount">₹ ${inr(a.quarterlyTds.Q2)}</td></tr>
<tr><td>Q3 (Oct–Dec)</td><td class="amount">₹ ${inr(a.quarterlyTds.Q3)}</td></tr>
<tr><td>Q4 (Jan–Mar)</td><td class="amount">₹ ${inr(a.quarterlyTds.Q4)}</td></tr>
<tr><td><strong>Total</strong></td><td class="amount"><strong>₹ ${inr(a.totalTdsDeposited)}</strong></td></tr>
</table>
<h2>Part B — Details of Salary Paid and Tax Deducted (${b.regime} regime)</h2>
<table>
${row("Gross Salary", b.grossSalary)}
${row("Standard Deduction (Sec 16)", b.standardDeduction)}
${row("HRA Exemption (Sec 10(13A))", b.hraExempt)}
${row("Deduction 80C", b.section80c)}
${row("Deduction 80D", b.section80d)}
${row("Other Chapter VI-A", b.otherDeductions)}
${row("Total Taxable Income", b.taxableIncome, true)}
${row("Tax on Income", b.taxOnIncome)}
${row("Rebate u/s 87A", b.rebate87A)}
${row("Surcharge", b.surcharge)}
${row("Health &amp; Education Cess (4%)", b.cess)}
${row("Total Tax Liability", b.totalTaxLiability, true)}
${row("Total TDS Deducted", b.totalTdsDeducted, true)}
${b.balanceTaxPayable > 0 ? row("Balance Tax Payable", b.balanceTaxPayable, true) : row("Refund Due", b.refundDue, true)}
</table>
<p style="font-size:11px;color:#666;margin-top:24px">${a.note} Generated by CivitasOne ERP — verify against TRACES before filing.</p>
</body></html>`;
}

export async function form16PdfRoutes(app: FastifyInstance): Promise<void> {
  app.get("/v1/payroll/tax/form16/:employeeId/pdf", async (req, reply) => {
    const ctx = resolveContext(req);
    requireRole(ctx, READER_ROLES);
    const { employeeId } = z.object({ employeeId: z.string().uuid() }).parse(req.params);
    const q = z.object({ fy: z.string().regex(/^\d{4}-\d{2}$/) }).parse(req.query);
    // M5: strict FY (suffix arithmetic) beyond the shape check above → 400.
    try { parseFy(q.fy); }
    catch { throw new HttpError(400, "VALIDATION_FAILED", "fy second component must be (startYear+1) mod 100, e.g. 2025-26"); }

    try {
      const f = await buildForm16(ctx.tenantId, employeeId, q.fy);
      return reply.header("content-type", "text/html; charset=utf-8").send(renderForm16(f));
    } catch (err) {
      // M4: HRMS unreachable → 502 (do not emit a blank-identity Form 16 PDF).
      if (err instanceof HrmsUnavailableError) {
        throw new HttpError(502, "HRMS_UNAVAILABLE", "cannot issue Form 16 PDF: HRMS identity source unreachable");
      }
      throw err;
    }
  });
}
