import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { resolveContext, requireRole, HttpError } from "../../shared/context.js";
import { eq, and } from "drizzle-orm";
import { db } from "../../shared/db.js";
import { payrollSlips } from "../payroll/schema.js";
import { payrollTds } from "../statutory/schema.js";
import { taxDeclarations } from "../tax/schema.js";

const READER_ROLES = ["payroll_admin", "payroll_officer", "super_admin", "hr_admin", "finance_officer", "employee"];

function renderTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => vars[key] ?? "");
}

const FORM16_TEMPLATE = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><title>Form 16 — FY {{fy}}</title>
<style>
body{font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:24px;font-size:13px}
h1{text-align:center;font-size:16px} h2{font-size:14px;margin-top:20px}
table{width:100%;border-collapse:collapse;margin:8px 0}
th,td{border:1px solid #333;padding:6px 8px}
.amount{text-align:right}
</style></head><body>
<h1>Form 16 — Certificate under Section 203</h1>
<p><strong>Employee ID:</strong> {{employeeId}} &nbsp; <strong>Financial Year:</strong> {{fy}}</p>
<h2>Part B — Details of Salary Paid and Tax Deducted</h2>
<table>
<tr><td>Gross Salary</td><td class="amount">₹ {{grossSalary}}</td></tr>
<tr><td>Standard Deduction</td><td class="amount">₹ {{standardDeduction}}</td></tr>
<tr><td>Section 80C</td><td class="amount">₹ {{section80c}}</td></tr>
<tr><td>Section 80D</td><td class="amount">₹ {{section80d}}</td></tr>
<tr><td>HRA Claimed</td><td class="amount">₹ {{hraClaimed}}</td></tr>
<tr><td><strong>Total TDS Deducted</strong></td><td class="amount"><strong>₹ {{totalTds}}</strong></td></tr>
</table>
<p style="font-size:11px;color:#666;margin-top:24px">Generated by CivitasOne ERP — verify against TRACES before filing</p>
</body></html>`;

export async function form16PdfRoutes(app: FastifyInstance): Promise<void> {
  app.get("/v1/payroll/tax/form16/:employeeId/pdf", async (req, reply) => {
    const ctx = resolveContext(req);
    requireRole(ctx, READER_ROLES);
    const { employeeId } = z.object({ employeeId: z.string().uuid() }).parse(req.params);
    const q = z.object({ fy: z.string().regex(/^\d{4}-\d{2}$/) }).parse(req.query);

    const tdsRows = await db.select().from(payrollTds)
      .where(and(eq(payrollTds.tenantId, ctx.tenantId), eq(payrollTds.employeeId, employeeId)));
    const totalTds = tdsRows.reduce((s, r) => s + Number(r.tdsMinor), 0) / 100;
    const slipRows = await db.select().from(payrollSlips)
      .where(and(eq(payrollSlips.tenantId, ctx.tenantId), eq(payrollSlips.employeeId, employeeId)));
    const annualGross = slipRows.reduce((s, r) => s + Number(r.grossMinor), 0) / 100;

    const decRows = await db.select().from(taxDeclarations)
      .where(and(
        eq(taxDeclarations.tenantId, ctx.tenantId),
        eq(taxDeclarations.employeeId, employeeId),
        eq(taxDeclarations.fy, q.fy),
      )).limit(1);
    const dec = decRows[0];

    const html = renderTemplate(FORM16_TEMPLATE, {
      employeeId,
      fy: q.fy,
      grossSalary: annualGross.toLocaleString("en-IN", { minimumFractionDigits: 2 }),
      standardDeduction: "50,000.00",
      section80c: dec ? (Math.min(Number(dec.section80c) / 100, 150000)).toLocaleString("en-IN", { minimumFractionDigits: 2 }) : "0.00",
      section80d: dec ? (Math.min(Number(dec.section80d) / 100, 50000)).toLocaleString("en-IN", { minimumFractionDigits: 2 }) : "0.00",
      hraClaimed: dec ? (Number(dec.hraClaimed) / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 }) : "0.00",
      totalTds: totalTds.toLocaleString("en-IN", { minimumFractionDigits: 2 }),
    });
    return reply.header("content-type", "text/html; charset=utf-8").send(html);
  });
}
