/**
 * report-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as jobsModule } from "../modules/jobs/schema.js";
import { schema as kpisModule } from "../modules/kpis/schema.js";
import { schema as templatesModule } from "../modules/templates/schema.js";
import { scheduledReportsSchema } from "../modules/scheduled/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...jobsModule,
  ...kpisModule,
  ...templatesModule,
  ...scheduledReportsSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
