/**
 * grant-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as schemeModule }       from "../modules/scheme/schema.js";
import { schema as applicationModule }  from "../modules/application/schema.js";
import { schema as disbursementModule } from "../modules/disbursement/schema.js";
import { schema as utilisationModule }  from "../modules/utilisation/schema.js";
import { schema as beneficiaryModule }  from "../modules/beneficiary/schema.js";
import { outboxSchema }                  from "./outbox.js";

const SCHEMA = {
  ...schemeModule,
  ...applicationModule,
  ...disbursementModule,
  ...utilisationModule,
  ...beneficiaryModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
