/**
 * crm-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as contactsModule } from "../modules/contacts/schema.js";
import { schema as dealsModule } from "../modules/deals/schema.js";
import { schema as activitiesModule } from "../modules/activities/schema.js";
import { schema as pipelinesModule } from "../modules/pipelines/schema.js";
import { schema as customFieldsModule } from "../modules/custom-fields/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...contactsModule,
  ...dealsModule,
  ...activitiesModule,
  ...pipelinesModule,
  ...customFieldsModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
