/**
 * crm-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as contactsModule } from "../modules/contacts/schema.js";
import { schema as dedupModule } from "../modules/contacts/dedup-schema.js";
import { schema as dealsModule } from "../modules/deals/schema.js";
import { schema as activitiesModule } from "../modules/activities/schema.js";
import { schema as pipelinesModule } from "../modules/pipelines/schema.js";
import { schema as customFieldsModule } from "../modules/custom-fields/schema.js";
import { schema as onboardingModule } from "../modules/onboarding/schema.js";
import { schema as sentimentModule } from "../modules/sentiment/schema.js";
import { schema as leadFieldRulesModule } from "../modules/leads/field-rules-schema.js";
import { schema as leadCaptureFormsModule } from "../modules/leads/capture-forms-schema.js";
import { schema as segmentEligibilityModule } from "../modules/segment-eligibility/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...contactsModule,
  ...dedupModule,
  ...dealsModule,
  ...activitiesModule,
  ...pipelinesModule,
  ...customFieldsModule,
  ...onboardingModule,
  ...sentimentModule,
  ...leadFieldRulesModule,
  ...leadCaptureFormsModule,
  ...segmentEligibilityModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Drizzle transaction handle exposed to {@link scopedRead} callbacks.
 * Preserves full column typing (the public db.transaction rewrites tx to any).
 */
type ScopedTx = Parameters<Parameters<typeof db.transaction>[0]>[0];
export type { ScopedTx };

/**
 * Run a READ inside a tenant transaction so PostgreSQL RLS is enforced on
 * the read path. A bare `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC — under FORCE ROW LEVEL SECURITY, it silently returns
 * zero rows. Wrapping in `db.transaction` makes the TenantRouter wrapper set
 * the GUC from AsyncLocalStorage, so reads are tenant-scoped by RLS.
 */
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn);
}
