-- Risk Register
CREATE TABLE IF NOT EXISTS project.project_risks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, title VARCHAR(256) NOT NULL, description TEXT, category VARCHAR(32) NOT NULL DEFAULT 'technical' CHECK (category IN ('technical','financial','environmental','social','regulatory','resource','schedule')), probability VARCHAR(8) NOT NULL DEFAULT 'medium' CHECK (probability IN ('low','medium','high','critical')), impact VARCHAR(8) NOT NULL DEFAULT 'medium' CHECK (impact IN ('low','medium','high','critical')), risk_score INT NOT NULL DEFAULT 0, mitigation_plan TEXT, owner_id UUID, status VARCHAR(16) NOT NULL DEFAULT 'open' CHECK (status IN ('open','mitigated','occurred','closed')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by UUID NOT NULL);
CREATE INDEX IF NOT EXISTS idx_proj_risks ON project.project_risks(tenant_id, project_id);

-- Earned Value Management (computed per milestone/period)
CREATE TABLE IF NOT EXISTS project.project_evm (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, period VARCHAR(7) NOT NULL, planned_value_minor BIGINT NOT NULL DEFAULT 0, earned_value_minor BIGINT NOT NULL DEFAULT 0, actual_cost_minor BIGINT NOT NULL DEFAULT 0, cpi NUMERIC(5,3), spi NUMERIC(5,3), eac_minor BIGINT, etc_minor BIGINT, variance_at_completion_minor BIGINT, computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(tenant_id, project_id, period));

-- Contractor Billing (RA Bills → Payment)
CREATE TABLE IF NOT EXISTS project.project_ra_bills (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, contractor_id UUID NOT NULL, contractor_name VARCHAR(256), bill_no VARCHAR(64) NOT NULL, bill_date DATE NOT NULL, work_description TEXT, gross_amount_minor BIGINT NOT NULL, deductions_minor BIGINT NOT NULL DEFAULT 0, net_amount_minor BIGINT NOT NULL, cumulative_minor BIGINT NOT NULL DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','verified','approved','paid','disputed')), verified_by UUID, approved_by UUID, payment_ref VARCHAR(128), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by UUID NOT NULL);

-- Time Extension
CREATE TABLE IF NOT EXISTS project.project_time_extensions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, original_end_date DATE NOT NULL, extended_end_date DATE NOT NULL, extension_days INT NOT NULL, reason TEXT NOT NULL, approved_by UUID, approval_date DATE, penalty_applicable BOOLEAN NOT NULL DEFAULT FALSE, penalty_per_day_minor BIGINT DEFAULT 0, status VARCHAR(16) NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','approved','rejected')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by UUID NOT NULL);

-- Penalty / Liquidated Damages
CREATE TABLE IF NOT EXISTS project.project_penalties (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, contractor_id UUID, penalty_type VARCHAR(32) NOT NULL DEFAULT 'delay' CHECK (penalty_type IN ('delay','quality','safety','other')), from_date DATE NOT NULL, to_date DATE NOT NULL, days INT NOT NULL, rate_per_day_minor BIGINT NOT NULL, total_minor BIGINT NOT NULL, recovered BOOLEAN NOT NULL DEFAULT FALSE, recovered_from VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by UUID NOT NULL);

-- Resource Allocation
CREATE TABLE IF NOT EXISTS project.project_resources (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, task_id UUID, resource_type VARCHAR(16) NOT NULL DEFAULT 'person' CHECK (resource_type IN ('person','equipment','material','vehicle')), resource_id UUID, resource_name VARCHAR(256) NOT NULL, allocated_hours NUMERIC(8,2), daily_rate_minor BIGINT DEFAULT 0, from_date DATE, to_date DATE, status VARCHAR(16) NOT NULL DEFAULT 'allocated' CHECK (status IN ('allocated','active','released')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- Baseline (snapshot of original plan)
CREATE TABLE IF NOT EXISTS project.project_baselines (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL, project_id UUID NOT NULL, baseline_no INT NOT NULL DEFAULT 1, snapshot_date DATE NOT NULL, planned_start DATE NOT NULL, planned_end DATE NOT NULL, planned_cost_minor BIGINT NOT NULL, milestones_snapshot JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_by UUID NOT NULL, UNIQUE(tenant_id, project_id, baseline_no));
