/**
 * billing-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as plansModule } from "../modules/plans/schema.js";
import { schema as subscriptionsModule } from "../modules/subscriptions/schema.js";
import { schema as usageModule } from "../modules/usage/schema.js";
import { schema as invoicesModule } from "../modules/invoices/schema.js";
import { schema as paymentsModule } from "../modules/payments/schema.js";
import { schema as einvoiceModule } from "../modules/einvoice/schema.js";
import { schema as revenueModule } from "../modules/revenue/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...plansModule,
  ...subscriptionsModule,
  ...usageModule,
  ...invoicesModule,
  ...paymentsModule,
  ...einvoiceModule,
  ...revenueModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes createTenantDb's
 * `wrapWithTenantGuc`-wrapped `db` set the GUC from AsyncLocalStorage -- reads
 * are then correctly tenant-scoped by RLS, not merely by an app-layer WHERE.
 * Preserved across the TenantRouter-adoption codemod so existing/future call
 * sites can keep importing this helper unchanged.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => PromiseLike<T>): Promise<T> {
  return db.transaction(fn as (tx: ScopedTx) => Promise<T>);
}
