/**
 * billing-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as plansModule } from "../modules/plans/schema.js";
import { schema as subscriptionsModule } from "../modules/subscriptions/schema.js";
import { schema as usageModule } from "../modules/usage/schema.js";
import { schema as invoicesModule } from "../modules/invoices/schema.js";
import { schema as paymentsModule } from "../modules/payments/schema.js";
import { schema as einvoiceModule } from "../modules/einvoice/schema.js";
import { schema as revenueModule } from "../modules/revenue/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...plansModule,
  ...subscriptionsModule,
  ...usageModule,
  ...invoicesModule,
  ...paymentsModule,
  ...einvoiceModule,
  ...revenueModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
