/**
 * identity-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { usersModuleSchema } from "../modules/users/schema.js";
import { rbacModuleSchema } from "../modules/rbac/schema.js";
import { sessionsModuleSchema } from "../modules/sessions/schema.js";
import { mfaModuleSchema } from "../modules/mfa/schema.js";
import { apiKeysModuleSchema } from "../modules/apikeys/schema.js";
import { breakglassModuleSchema } from "../modules/breakglass/schema.js";
import { schema as devicesSyncSchema } from "../modules/devices/schema.js";
import { outboxSchema } from "./outbox.js";
import { kcReconcileSchema } from "./kc-reconcile.js";

const SCHEMA = {
  ...usersModuleSchema,
  ...rbacModuleSchema,
  ...sessionsModuleSchema,
  ...mfaModuleSchema,
  ...apiKeysModuleSchema,
  ...breakglassModuleSchema,
  ...devicesSyncSchema,
  ...outboxSchema,
  ...kcReconcileSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
