/**
 * identity-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { usersModuleSchema } from "../modules/users/schema.js";
import { rbacModuleSchema } from "../modules/rbac/schema.js";
import { sessionsModuleSchema } from "../modules/sessions/schema.js";
import { mfaModuleSchema } from "../modules/mfa/schema.js";
import { apiKeysModuleSchema } from "../modules/apikeys/schema.js";
import { breakglassModuleSchema } from "../modules/breakglass/schema.js";
import { schema as devicesSyncSchema } from "../modules/devices/schema.js";
import { outboxSchema } from "./outbox.js";
import { kcReconcileSchema } from "./kc-reconcile.js";

const SCHEMA = {
  ...usersModuleSchema,
  ...rbacModuleSchema,
  ...sessionsModuleSchema,
  ...mfaModuleSchema,
  ...apiKeysModuleSchema,
  ...breakglassModuleSchema,
  ...devicesSyncSchema,
  ...outboxSchema,
  ...kcReconcileSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain db.select() runs on a pooled connection with no
 * app.tenant_id GUC set, so under a NOBYPASSRLS role (hrms_svc / identity_svc)
 * the fail-closed policy returns ZERO rows. Wrapping the read in db.transaction
 * makes createTenantDb's `wrapWithTenantGuc`-wrapped `db` set the GUC from
 * AsyncLocalStorage - reads are then correctly tenant-scoped by RLS, not merely
 * by an app-layer WHERE. Mirrors court-service / visitor-service / meeting-service.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<Db["transaction"]>[0]) as Promise<T>;
}
