/**
 * analytics-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as dashboardsModule } from "../modules/dashboards/schema.js";
import { schema as queriesModule } from "../modules/queries/schema.js";
import { schema as metricsModule } from "../modules/metrics/schema.js";
import { schema as factsModule } from "../modules/facts/schema.js";
import { schema as exportsModule } from "../modules/exports/schema.js";
import { scheduledExportsSchema } from "../modules/exports/scheduled-schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...dashboardsModule,
  ...queriesModule,
  ...metricsModule,
  ...factsModule,
  ...exportsModule,
  ...scheduledExportsSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain db.select() runs on a pooled connection with no
 * app.tenant_id GUC set, so under a NOBYPASSRLS role (analytics_svc) the
 * fail-closed policy returns ZERO rows. Wrapping the read in db.transaction
 * makes wrapWithTenantGuc set the GUC from AsyncLocalStorage - reads are then
 * correctly tenant-scoped by RLS, not merely by an app-layer WHERE. Mirrors
 * hrms-service / payroll-service / workflow-service.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<Db["transaction"]>[0]) as Promise<T>;
}
