/**
 * analytics-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as dashboardsModule } from "../modules/dashboards/schema.js";
import { schema as queriesModule } from "../modules/queries/schema.js";
import { schema as metricsModule } from "../modules/metrics/schema.js";
import { schema as factsModule } from "../modules/facts/schema.js";
import { schema as exportsModule } from "../modules/exports/schema.js";
import { scheduledExportsSchema } from "../modules/exports/scheduled-schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...dashboardsModule,
  ...queriesModule,
  ...metricsModule,
  ...factsModule,
  ...exportsModule,
  ...scheduledExportsSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
