/**
 * helpdesk-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as ticketsModule } from "../modules/tickets/schema.js";
import { schema as automationModule } from "../modules/automation/schema.js";
import { schema as slaModule } from "../modules/sla/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...ticketsModule,
  ...automationModule,
  ...slaModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
