/**
 * helpdesk-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as ticketsModule } from "../modules/tickets/schema.js";
import { schema as automationModule } from "../modules/automation/schema.js";
import { schema as slaModule } from "../modules/sla/schema.js";
import { schema as catalogueModule } from "../modules/catalogue/schema.js";
import { savedViewsSchema } from "../modules/tickets/views-schema.js";
import { knowledgeSchema } from "../modules/knowledge/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...ticketsModule,
  ...automationModule,
  ...slaModule,
  ...catalogueModule,
  ...savedViewsSchema,
  ...knowledgeSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside a transaction so PostgreSQL RLS is enforced on the read
 * path. Plain `db.select()` runs on a pooled connection with no `app.tenant_id`
 * GUC set, so RLS fail-closed policies return ZERO rows. Wrapping in
 * `db.transaction()` lets createTenantDb's wrapWithTenantGuc set the GUC from
 * AsyncLocalStorage when a tenant context is active. When no context is active
 * (cross-tenant sweepers), the transaction passes through without GUC — which
 * still works with pooled connections that have direct table access.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => PromiseLike<T>): Promise<T> {
  return db.transaction(fn as (tx: ScopedTx) => Promise<T>);
}
