import { randomUUID } from "node:crypto";
import type { RequestContext } from "@civitasone/types";
import { queue, cache } from "../../shared/infra.js";
import { COMMANDS } from "../../topics.js";
import type { GeoTagBody, PhotoUploadBody } from "./validators.js";

export type Accepted = { id: string; status: string; correlationId: string };
export type PresignedUrlResponse = { id: string; uploadUrl: string; s3Key: string; correlationId: string };

const S3_BUCKET = process.env.S3_BUCKET ?? "civitasone-site-photos";

export async function geoTag(ctx: RequestContext, projectId: string, body: GeoTagBody): Promise<Accepted> {
  const id = randomUUID();
  await queue.publish(COMMANDS.geoTag, {
    messageId: id, type: COMMANDS.geoTag,
    tenantId: ctx.tenantId, actorId: ctx.actorId, correlationId: ctx.correlationId, schemaVersion: "1.0",
    payload: { id, tenantId: ctx.tenantId, projectId, taggedBy: ctx.actorId, ...body },
  });
  await cache.invalidate(cache.makeKey(ctx.tenantId, "geo", projectId));
  return { id, status: "accepted", correlationId: ctx.correlationId };
}

export async function requestPhotoUpload(ctx: RequestContext, projectId: string, body: PhotoUploadBody): Promise<PresignedUrlResponse> {
  const id = randomUUID();
  const s3Key = `projects/${projectId}/${id}/${body.originalName}`;
  await queue.publish(COMMANDS.photoUpload, {
    messageId: id, type: COMMANDS.photoUpload,
    tenantId: ctx.tenantId, actorId: ctx.actorId, correlationId: ctx.correlationId, schemaVersion: "1.0",
    payload: { id, tenantId: ctx.tenantId, projectId, s3Key, uploadedBy: ctx.actorId, ...body },
  });
  // Return pre-signed URL placeholder; real URL generated by consumer via S3 adapter
  return {
    id,
    uploadUrl: `https://${S3_BUCKET}.s3.amazonaws.com/${s3Key}?presigned=placeholder`,
    s3Key,
    correlationId: ctx.correlationId,
  };
}
