/**
 * audit-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { eventsModuleSchema } from "../modules/events/schema.js";
import { exportsModuleSchema } from "../modules/exports/schema.js";
import { schema as planModule } from "../modules/plan/schema.js";
import { schema as observationModule } from "../modules/observation/schema.js";
import { schema as paraModule } from "../modules/para/schema.js";
import { schema as complianceModule } from "../modules/compliance/schema.js";
import { schema as riskModule } from "../modules/risk/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...eventsModuleSchema,
  ...exportsModuleSchema,
  ...planModule,
  ...observationModule,
  ...paraModule,
  ...complianceModule,
  ...riskModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
