// AUTO-GENERATED — do not hand-edit path entries.
//
// The set of ancestor route paths that (a) appear as an intermediate breadcrumb
// crumb somewhere in the app AND (b) actually have their own index `page.tsx`,
// so navigating to them resolves instead of 404-ing.
//
// WHY THIS EXISTS: <AutoBreadcrumb> builds a crumb for every ancestor segment of
// the current path. Several ancestor segments are pure groupings with children
// but NO index page (e.g. /finance/budget, /finance/treasury, /estab/files,
// /legal/cases). Linking those crumbs sent the clerk to a dead 404 route. The
// breadcrumb now links an intermediate crumb ONLY when its path is in this set,
// and otherwise renders the label as plain (non-clickable) context text.
//
// SAFE DEGRADATION: this allowlist can go mildly stale without ever causing a
// 404 or a wrong link — a missing entry only downgrades a real link to plain
// text. Regenerate with:  node scripts/gen-nav-route-manifest.mjs
// (from apps/web). Kept intentionally free of a filesystem-freshness test so it
// never couples this shared component's CI to unrelated route additions.

export const LINKABLE_INTERMEDIATE_PATHS: ReadonlySet<string> = new Set([
  "/admin",
  "/ai",
  "/analytics",
  "/analytics/ml-insights",
  "/assets",
  "/assets/fleet",
  "/assets/insurance",
  "/assets/maintenance",
  "/audit",
  "/billing",
  "/billing/plans",
  "/catalogue",
  "/cdp",
  "/change",
  "/citizen",
  "/citizen/grievances",
  "/contracts",
  "/court",
  "/crm",
  "/crm/contacts",
  "/crm/deals",
  "/crm/grievances",
  "/crm/opportunities",
  "/crm/rti",
  "/crm/service-requests",
  "/crm/voice-of-customer",
  "/designer",
  "/documents",
  "/estab",
  "/estab/library",
  "/estab/quarters",
  "/establishment",
  "/field",
  "/finance",
  "/finance/budget/formulation",
  "/finance/chart-of-accounts",
  "/finance/expenditure/advances",
  "/finance/expenditure/utilization-certificates",
  "/fleet",
  "/grants",
  "/grants/schemes",
  "/helpdesk",
  "/helpdesk/catalogue",
  "/helpdesk/tickets",
  "/hr",
  "/hr/apar",
  "/hr/appraisals",
  "/hr/attendance",
  "/hr/departments",
  "/hr/designations",
  "/hr/employees",
  "/hr/jd-templates",
  "/hr/leave",
  "/hr/locations",
  "/hr/overtime",
  "/hr/payroll",
  "/hr/payroll/pensioners",
  "/hr/payroll/statutory",
  "/hr/recruitment",
  "/hr/shifts",
  "/hr/training",
  "/hr/workforce",
  "/hr/workforce/overtime",
  "/identity",
  "/inspection",
  "/install",
  "/inventory",
  "/journeys",
  "/knowledge",
  "/learning",
  "/learning/assessments",
  "/legal",
  "/legal/court-orders",
  "/legal/opinions",
  "/locations",
  "/locations/maps",
  "/loyalty",
  "/meeting",
  "/meeting/meetings",
  "/metadata",
  "/notifications",
  "/platform-admin",
  "/plugins",
  "/policy",
  "/procurement",
  "/procurement/approvals",
  "/procurement/contracts",
  "/procurement/grn",
  "/procurement/indents",
  "/procurement/orders",
  "/procurement/planning",
  "/procurement/rfq",
  "/procurement/tenders",
  "/procurement/vendors",
  "/projects",
  "/recommendations",
  "/reports",
  "/reports/list",
  "/revenue",
  "/stock",
  "/stock/ledger",
  "/telephony",
  "/tenant",
  "/tenant-admin",
  "/tenant-admin/notifications",
  "/themes",
  "/visitor",
  "/workflow",
  "/works",
  "/works/approvals",
  "/works/billing",
  "/works/boq",
  "/works/contractors",
  "/works/execution",
  "/works/execution/issues",
  "/works/proposals",
  "/works/tenders",
]);

/** True when an intermediate breadcrumb crumb at `path` resolves to a real page. */
export function isLinkableCrumb(path: string): boolean {
  return LINKABLE_INTERMEDIATE_PATHS.has(path);
}
