/**
 * KPI, Data Warehouse, and AI Insights read-only routes.
 * Previously these were mock pages with hardcoded arrays.
 */
import type { FastifyInstance } from "fastify";
import { resolveContext, requireRole } from "../../shared/context.js";
import { cache } from "../../shared/infra.js";
import { scopedRead } from "../../shared/db.js";
import { savedMetrics } from "../metrics/schema.js";
import { factEvents } from "../facts/schema.js";
import { eq, count, max } from "drizzle-orm";
import { runWithTenant } from "@civitasone/db";
// GAP2-ANALYTICS-ROLES-01: single canonical reader vocabulary across every
// analytics read route (union of the two historical names so no existing
// principal loses access). Previously this file used a bare
// ["analytics_viewer", ...] array that did NOT include "analytics_user".
import { ANALYTICS_READ_ROLES as READ_ROLES } from "../../shared/roles.js";

function paginationMeta(total: number, page: number, pageSize: number) {
  return { page, pageSize, total };
}

export async function kpiRoutes(app: FastifyInstance): Promise<void> {
  // ─── KPI Library ────────────────────────────────────────────────────────────
  app.get("/v1/analytics/kpis", async (req, reply) => {
    const ctx = resolveContext(req);
    requireRole(ctx, READ_ROLES);
    const tenantId = ctx.tenantId;

    const rows = await cache.getOrLoad(
      cache.makeKey(tenantId, "analytics", "kpis"),
      async () => {
        const result = await runWithTenant(tenantId, () => scopedRead(async (tx) =>
          tx.select({
            id: savedMetrics.id,
            name: savedMetrics.name,
            metricKey: savedMetrics.metricKey,
          }).from(savedMetrics)
            .where(eq(savedMetrics.tenantId, tenantId))
            .orderBy(savedMetrics.name)
            .limit(200),
        ));
        return result.map((r) => ({
          kpiName: r.name,
          category: r.metricKey?.split(".")[0] ?? "General",
          currentValue: "—",
          target: "—",
          trend: "—",
          owner: "—",
        }));
      },
    );

    return reply.send({ data: rows ?? [], meta: paginationMeta((rows ?? []).length, 1, 200) });
  });

  // ─── Data Warehouse (dataset summary) ──────────────────────────────────────
  app.get("/v1/analytics/data-warehouse", async (req, reply) => {
    const ctx = resolveContext(req);
    requireRole(ctx, READ_ROLES);
    const tenantId = ctx.tenantId;

    const rows = await cache.getOrLoad(
      cache.makeKey(tenantId, "analytics", "data-warehouse"),
      async () => {
        // Summarize fact_events by source module. GAP2-ANALYTICS-DATA-WAREHOUSE-01:
        // `lastRefresh` is derived from the real max(occurred_at) of each
        // source's fact_events — NOT request time. The old
        // `new Date().toISOString()` stamped "now" on every request, falsely
        // implying a just-completed refresh. `size`/`qualityScore` remain "—"
        // (no real signal exists), and `status` is now "—" (unknown) rather
        // than a blanket "Healthy" that made the page's Attention count
        // structurally always 0.
        const result = await runWithTenant(tenantId, () => scopedRead(async (tx) =>
          tx.select({
            source: factEvents.source,
            recordCount: count(factEvents.id),
            lastOccurredAt: max(factEvents.occurredAt),
          }).from(factEvents)
            .where(eq(factEvents.tenantId, tenantId))
            .groupBy(factEvents.source)
            .orderBy(factEvents.source)
            .limit(50),
        ));
        return result.map((r) => {
          const last = r.lastOccurredAt
            ? new Date(r.lastOccurredAt as unknown as string | Date)
            : null;
          return {
            dataset: r.source ?? "Unknown",
            lastRefresh: last ? last.toISOString().slice(0, 16).replace("T", " ") : "—",
            records: String(r.recordCount),
            size: "—",
            qualityScore: "—",
            status: "—",
          };
        });
      },
    );

    return reply.send({ data: rows ?? [], meta: paginationMeta((rows ?? []).length, 1, 50) });
  });

  // ─── AI Insights ───────────────────────────────────────────────────────────
  app.get("/v1/analytics/ai-insights", async (req, reply) => {
    const ctx = resolveContext(req);
    requireRole(ctx, READ_ROLES);
    const tenantId = ctx.tenantId;

    // AI insights are generated asynchronously; this endpoint returns persisted results.
    // When no insights exist, the page will show EmptyState.
    const rows = await cache.getOrLoad(
      cache.makeKey(tenantId, "analytics", "ai-insights"),
      async () => {
        // Return empty for now — AI insights are generated by a separate scheduled process
        // gated behind FEATURE_AI_ASSISTANT_ENABLED
        return [] as Array<{
          insightTitle: string;
          module: string;
          confidence: string;
          generatedDate: string;
          actionRecommended: string;
          status: string;
        }>;
      },
    );

    return reply.send({ data: rows ?? [], meta: paginationMeta((rows ?? []).length, 1, 200) });
  });
}
