/**
 * visitor-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { outboxSchema } from "./outbox.js";
import { schema as checkInModule } from "../modules/check-in/schema.js";
import { schema as digitalPassModule } from "../modules/digital-pass/schema.js";
import { schema as visitRequestModule } from "../modules/visit-request/schema.js";
import { schema as locationModule } from "../modules/location/schema.js";
import { schema as dpdpModule } from "../modules/dpdp/schema.js";
import { blacklistEntries, watchlistEntries } from "../modules/blacklist/schema.js";
import { schema as analyticsModule } from "../modules/analytics/schema.js";

const SCHEMA = {
  ...checkInModule,
  ...digitalPassModule,
  ...visitRequestModule,
  ...locationModule,
  ...dpdpModule,
  ...analyticsModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
