export const COMMANDS = {
  createInstance: "workflow.instance.create",
  completeTask: "workflow.task.complete",
  cancelInstance: "workflow.instance.cancel",
  suspendInstance: "workflow.instance.suspend",
  resumeInstance: "workflow.instance.resume",
  deliverMessage: "workflow.message.deliver",
  correlateMessage: "workflow.message.correlate",
  broadcastSignal: "workflow.signal.broadcast",
  // CQRS (designer lift) — BPMN visual designer definition writes.
  createDesignerDefinition: "workflow.designer.definition.create",
  updateDesignerDefinition: "workflow.designer.definition.update",
  deleteDesignerDefinition: "workflow.designer.definition.delete",
  importDesignerDefinition: "workflow.designer.definition.import",
  createDefinition: "workflow.definition.create",
  deployDefinition: "workflow.definition.deploy",
  cloneDefinitionTemplate: "workflow.definition.clone",
  rollbackDefinition: "workflow.definition.rollback",
  importBpmnDefinition: "workflow.definition.bpmn_import",
  createDmnTable: "workflow.dmn.table.create",
  updateDmnTable: "workflow.dmn.table.update",
  deleteDmnTable: "workflow.dmn.table.delete",
  upsertRoleMember: "workflow.role_member.upsert",
  createMatrixRule: "workflow.assignment.matrix.create",
  deactivateMatrixRule: "workflow.assignment.matrix.deactivate",
  createSubstitution: "workflow.assignment.substitution.create",
  deactivateSubstitution: "workflow.assignment.substitution.deactivate",
  createDecision: "workflow.decision.create",
  deployDecision: "workflow.decision.deploy",
  // F3 leftover CQRS — delegations/authority/finalization/quorum/sla/deviations/workbaskets
  createDelegation: "workflow.delegation.create",
  revokeDelegation: "workflow.delegation.revoke",
  createAuthorityLimit: "workflow.authority.limit.create",
  approveAuthorityLimit: "workflow.authority.limit.approve",
  revokeAuthorityLimit: "workflow.authority.limit.revoke",
  finalizeInstance: "workflow.instance.finalize",
  reverseInstance: "workflow.instance.reverse",
  createCommitteeDecision: "workflow.committee.decision.create",
  castCommitteeVote: "workflow.committee.vote.cast",
  createCalendar: "workflow.calendar.create",
  pauseTaskSla: "workflow.task.sla.pause",
  resumeTaskSla: "workflow.task.sla.resume",
  raiseDeviation: "workflow.deviation.raise",
  reviewDeviation: "workflow.deviation.review",
  revokeDeviation: "workflow.deviation.revoke",
  upsertWorkbasket: "workflow.workbasket.upsert",
  // P0 F3 leftover — case-links / checklists / comments
  createCaseLink: "workflow.case.link.create",
  splitCase: "workflow.case.split",
  mergeCases: "workflow.case.merge",
  upsertChecklistTemplate: "workflow.checklist.template.upsert",
  createChecklistInstance: "workflow.checklist.instance.create",
  toggleChecklistItem: "workflow.checklist.item.toggle",
  addComment: "workflow.comment.add",
  editComment: "workflow.comment.edit",
  deleteComment: "workflow.comment.delete",
} as const;

export const EVENTS = {
  instanceCreated: "workflow.instance.created",
  taskCompleted: "workflow.task.completed",
  taskAssigned: "workflow.task.assigned",
  instanceCancelled: "workflow.instance.cancelled",
  instanceRejected: "workflow.instance.rejected",
  instanceSuspended: "workflow.instance.suspended",
  instanceResumed: "workflow.instance.resumed",
  messageDelivered: "workflow.message.delivered",
  messageReceived: "workflow.message.received",
  signalDelivered: "workflow.signal.delivered",
  signalReceived: "workflow.signal.received",
  messageTimeout: "workflow.message.timeout",
  // CAP-026 — a committee/quorum decision settled.
  committeeDecided: "workflow.committee.decided",
  // CAP-025 — a request exceeded the actor's authority and was escalated.
  authorityEscalated: "workflow.authority.escalated",
  // CAP-029 — instance finalization / reversal.
  instanceFinalized: "workflow.instance.finalized",
  instanceReversed: "workflow.instance.reversed",
  // CQRS (designer lift) — BPMN visual designer definition lifecycle events.
  designerDefinitionCreated: "workflow.designer.definition.created",
  designerDefinitionUpdated: "workflow.designer.definition.updated",
  designerDefinitionDeleted: "workflow.designer.definition.deleted",
  designerDefinitionImported: "workflow.designer.definition.imported",
  definitionCreated: "workflow.definition.created",
  definitionDeployed: "workflow.definition.deployed",
  definitionCloned: "workflow.definition.cloned",
  definitionRolledBack: "workflow.definition.rolled_back",
  definitionBpmnImported: "workflow.definition.bpmn_imported",
  dmnTableCreated: "workflow.dmn.table.created",
  dmnTableUpdated: "workflow.dmn.table.updated",
  dmnTableDeleted: "workflow.dmn.table.deleted",
  roleMemberUpserted: "workflow.role_member.upserted",
  matrixRuleCreated: "workflow.assignment.matrix.created",
  matrixRuleDeactivated: "workflow.assignment.matrix.deactivated",
  substitutionCreated: "workflow.assignment.substitution.created",
  substitutionDeactivated: "workflow.assignment.substitution.deactivated",
  decisionCreated: "workflow.decision.created",
  decisionDeployed: "workflow.decision.deployed",
  delegationCreated: "workflow.delegation.created",
  delegationRevoked: "workflow.delegation.revoked",
  authorityLimitCreated: "workflow.authority.limit.created",
  authorityLimitApproved: "workflow.authority.limit.approved",
  authorityLimitRevoked: "workflow.authority.limit.revoked",
  calendarCreated: "workflow.calendar.created",
  taskSlaPaused: "workflow.task.sla.paused",
  taskSlaResumed: "workflow.task.sla.resumed",
  deviationRaised: "workflow.deviation.raised",
  deviationReviewed: "workflow.deviation.reviewed",
  deviationRevoked: "workflow.deviation.revoked",
  workbasketUpserted: "workflow.workbasket.upserted",
  caseLinkCreated: "workflow.case.link.created",
  caseSplit: "workflow.case.split",
  casesMerged: "workflow.case.merged",
  checklistTemplateUpserted: "workflow.checklist.template.upserted",
  checklistInstanceCreated: "workflow.checklist.instance.created",
  checklistItemToggled: "workflow.checklist.item.toggled",
  commentAdded: "workflow.comment.added",
  commentEdited: "workflow.comment.edited",
  commentDeleted: "workflow.comment.deleted",
} as const;

/** Cross-service commands dispatched when a workflow task completes. */
export const DISPATCH = {
  leaveApprove: "hrms.leave.approve",
  payrollRunApprove: "payroll.run.approve",
  indentApprove: "procurement.indent.approve",
  poApprove: "procurement.po.approve",
  fileApprove: "estab.file.approve",
  fileReject: "estab.file.reject",
  fileLevelApproved: "estab.file.level_approved",
  assetDisposeApprove: "asset.dispose.approve",
} as const;

export const SERVICE = "workflow";
export const INSTANCE_RESOURCE = "instance";
export const TASK_RESOURCE = "task";

/** Events consumed from other services. */
export const CONSUMED_EVENTS = {
  tenantCreated: "tenant.tenant.created",
} as const;
