/**
 * payroll-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { sql } from "drizzle-orm";
import { createTenantDb } from "@civitasone/db";
import { schema as payrollModule }    from "../modules/payroll/schema.js";
import { schema as loansModule }      from "../modules/loans/schema.js";
import { schema as statutoryModule }  from "../modules/statutory/schema.js";
import { schema as integrationModule } from "../modules/integration/schema.js";
import { schema as taxModule }         from "../modules/tax/schema.js";
import { schema as sponsorConfigModule } from "../modules/sponsor-config/schema.js";
import { schema as nachReturnModule } from "../modules/nach-return/schema.js";
import { schema as dscConfigModule } from "../modules/dsc-config/schema.js";
import { outboxSchema }               from "./outbox.js";

const SCHEMA = {
  ...payrollModule,
  ...loansModule,
  ...statutoryModule,
  ...integrationModule,
  ...taxModule,
  ...sponsorConfigModule,
  ...nachReturnModule,
  ...dscConfigModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes the wrapper
 * above set the GUC from AsyncLocalStorage — reads are then correctly
 * tenant-scoped by RLS, not merely by an app-layer WHERE.
 */
type ScopedTx = Parameters<Parameters<typeof db.transaction>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<typeof db.transaction>[0]) as Promise<T>;
}

/**
 * DOM-008 (completing #1117): run a genuinely cross-tenant SELECT (the
 * trusted boot-time load of payroll.tax_slab_config into the in-memory tax
 * engine registry — config.ts's loadTaxConfig() — which must see every
 * tenant's rows plus the platform default in one query) with the
 * `app.platform_bypass` GUC set for the transaction, per the additional
 * permissive SELECT-only RLS policy in migration
 * 0039_tax_slab_config_tenant_scope.sql. Mirrors audit-service's
 * scopedPlatformRead / migration 0021 and this service's own migration 0037
 * exactly.
 *
 * SECURITY: this must ONLY be called from trusted server-side code with no
 * user-supplied input — never derived from a request header/param/JWT claim.
 * It is SELECT-only by policy design: INSERT/UPDATE/DELETE on tax_slab_config
 * remain governed solely by the strict tenant-match policy, so this can never
 * let a write skip tenant scoping.
 */
export function scopedPlatformRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(async (tx) => {
    await (tx as unknown as { execute: (q: unknown) => Promise<unknown> }).execute(
      sql`SELECT set_config('app.platform_bypass', 'true', true)`,
    );
    return fn(tx);
  }) as Promise<T>;
}
