/**
 * payroll-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as payrollModule }    from "../modules/payroll/schema.js";
import { schema as loansModule }      from "../modules/loans/schema.js";
import { schema as statutoryModule }  from "../modules/statutory/schema.js";
import { schema as integrationModule } from "../modules/integration/schema.js";
import { schema as taxModule }         from "../modules/tax/schema.js";
import { schema as sponsorConfigModule } from "../modules/sponsor-config/schema.js";
import { schema as nachReturnModule } from "../modules/nach-return/schema.js";
import { schema as dscConfigModule } from "../modules/dsc-config/schema.js";
import { outboxSchema }               from "./outbox.js";

const SCHEMA = {
  ...payrollModule,
  ...loansModule,
  ...statutoryModule,
  ...integrationModule,
  ...taxModule,
  ...sponsorConfigModule,
  ...nachReturnModule,
  ...dscConfigModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes the wrapper
 * above set the GUC from AsyncLocalStorage — reads are then correctly
 * tenant-scoped by RLS, not merely by an app-layer WHERE.
 */
type ScopedTx = Parameters<Parameters<typeof db.transaction>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<typeof db.transaction>[0]) as Promise<T>;
}
