import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { sql } from "drizzle-orm";
import { resolveContext, requireRole, HttpError } from "../../shared/context.js";
import { db } from "../../shared/db.js";
const ROLES = ["payroll_admin","payroll_officer","super_admin","hr_admin"];
export async function worldClassPayrollRoutes(app: FastifyInstance): Promise<void> {
  // Arrears
  app.get("/v1/payroll/arrears", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_arrears WHERE tenant_id=${ctx.tenantId}::uuid ORDER BY created_at DESC LIMIT 100`); return reply.send({data:rows}); });
  app.post("/v1/payroll/arrears", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const body = z.object({employeeId:z.string().uuid(),componentCode:z.string(),fromPeriod:z.string(),toPeriod:z.string(),oldAmountMinor:z.number().int(),newAmountMinor:z.number().int(),reason:z.string().optional()}).parse(req.body); const diff=body.newAmountMinor-body.oldAmountMinor; const rows = await db.execute(sql`INSERT INTO payroll.payroll_arrears(tenant_id,employee_id,component_code,from_period,to_period,old_amount_minor,new_amount_minor,difference_minor,reason,created_by) VALUES(${ctx.tenantId}::uuid,${body.employeeId}::uuid,${body.componentCode},${body.fromPeriod},${body.toPeriod},${body.oldAmountMinor},${body.newAmountMinor},${diff},${body.reason??null},${ctx.actorId}::uuid) RETURNING id,difference_minor,status`); return reply.code(201).send({data:(rows as any)[0]}); });
  // Bonus
  app.get("/v1/payroll/bonus", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const q=z.object({fy:z.string().optional()}).parse(req.query); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_bonus WHERE tenant_id=${ctx.tenantId}::uuid AND (${q.fy??null}::text IS NULL OR fy=${q.fy??null}) ORDER BY created_at DESC`); return reply.send({data:rows}); });
  app.post("/v1/payroll/bonus/compute", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const body=z.object({employeeId:z.string().uuid(),fy:z.string(),basicMinor:z.number().int(),bonusPct:z.number().default(8.33)}).parse(req.body); const amt=Math.round(body.basicMinor*body.bonusPct/100); const rows = await db.execute(sql`INSERT INTO payroll.payroll_bonus(tenant_id,employee_id,fy,basic_minor,bonus_pct,bonus_amount_minor) VALUES(${ctx.tenantId}::uuid,${body.employeeId}::uuid,${body.fy},${body.basicMinor},${body.bonusPct},${amt}) RETURNING id,bonus_amount_minor,status`); return reply.code(201).send({data:(rows as any)[0]}); });
  // Professional Tax
  app.get("/v1/payroll/statutory/pt", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_professional_tax WHERE tenant_id=${ctx.tenantId}::uuid AND is_active=true ORDER BY state_code,slab_from_minor`); return reply.send({data:rows}); });
  // LWF
  app.get("/v1/payroll/statutory/lwf", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_lwf WHERE tenant_id=${ctx.tenantId}::uuid ORDER BY state_code`); return reply.send({data:rows}); });
  // Reimbursements
  app.get("/v1/payroll/reimbursements", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const q=z.object({employeeId:z.string().uuid().optional(),status:z.string().optional()}).parse(req.query); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_reimbursements WHERE tenant_id=${ctx.tenantId}::uuid AND (${q.employeeId??null}::uuid IS NULL OR employee_id=${q.employeeId??null}::uuid) AND (${q.status??null}::text IS NULL OR status=${q.status??null}) ORDER BY created_at DESC LIMIT 100`); return reply.send({data:rows}); });
  app.post("/v1/payroll/reimbursements", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, [...ROLES,"employee"]); const body=z.object({employeeId:z.string().uuid(),category:z.enum(["medical","travel","lta","food","telephone","internet","fuel","other"]),amountMinor:z.number().int().positive(),billDate:z.string().optional(),billRef:z.string().optional(),period:z.string()}).parse(req.body); const rows = await db.execute(sql`INSERT INTO payroll.payroll_reimbursements(tenant_id,employee_id,category,amount_minor,bill_date,bill_ref,period,created_by) VALUES(${ctx.tenantId}::uuid,${body.employeeId}::uuid,${body.category},${body.amountMinor},${body.billDate??null}::date,${body.billRef??null},${body.period},${ctx.actorId}::uuid) RETURNING id,category,amount_minor,status`); return reply.code(201).send({data:(rows as any)[0]}); });
  // Salary Revisions
  app.get("/v1/payroll/salary-revisions", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const q=z.object({employeeId:z.string().uuid().optional()}).parse(req.query); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_salary_revisions WHERE tenant_id=${ctx.tenantId}::uuid AND (${q.employeeId??null}::uuid IS NULL OR employee_id=${q.employeeId??null}::uuid) ORDER BY effective_date DESC LIMIT 100`); return reply.send({data:rows}); });
  // Payroll Register (department summary)
  app.get("/v1/payroll/register", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const q=z.object({period:z.string().optional(),runId:z.string().uuid().optional()}).parse(req.query); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_register WHERE tenant_id=${ctx.tenantId}::uuid AND (${q.period??null}::text IS NULL OR period=${q.period??null}) AND (${q.runId??null}::uuid IS NULL OR run_id=${q.runId??null}::uuid) ORDER BY department_name`); return reply.send({data:rows}); });
  // CTC Calculator
  app.get("/v1/payroll/ctc/config", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const rows = await db.execute(sql`SELECT * FROM payroll.payroll_ctc_config WHERE tenant_id=${ctx.tenantId}::uuid AND is_active=true ORDER BY component_code`); return reply.send({data:rows}); });
  app.post("/v1/payroll/ctc/calculate", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const body=z.object({ctcMinor:z.number().int().positive()}).parse(req.body); const config = await db.execute(sql`SELECT * FROM payroll.payroll_ctc_config WHERE tenant_id=${ctx.tenantId}::uuid AND is_active=true ORDER BY component_code`); const comps=(config as any[]).map((c:any)=>{let amt=0;if(c.calc_type==='pct_of_ctc')amt=Math.round(body.ctcMinor*Number(c.value)/100);else if(c.calc_type==='pct_of_basic'){const basic=Math.round(body.ctcMinor*40/100);amt=Math.round(basic*Number(c.value)/100);}else amt=Math.round(Number(c.value));return{code:c.component_code,name:c.component_name,amountMinor:amt,isEmployerCost:c.is_employer_cost};}); const gross=comps.filter((c:any)=>!c.isEmployerCost).reduce((s:number,c:any)=>s+c.amountMinor,0); const employerCost=comps.filter((c:any)=>c.isEmployerCost).reduce((s:number,c:any)=>s+c.amountMinor,0); return reply.send({ctcMinor:body.ctcMinor,grossMinor:gross,employerCostMinor:employerCost,components:comps}); });
  // Payroll Comparison (month-on-month)
  app.get("/v1/payroll/comparison", async (req, reply) => { const ctx = resolveContext(req); requireRole(ctx, ROLES); const q=z.object({period1:z.string(),period2:z.string()}).parse(req.query); const r1 = await db.execute(sql`SELECT COALESCE(SUM(total_gross_minor),0)::bigint as gross,COALESCE(SUM(total_net_minor),0)::bigint as net,COALESCE(SUM(employee_count),0)::int as headcount FROM payroll.payroll_register WHERE tenant_id=${ctx.tenantId}::uuid AND period=${q.period1}`); const r2 = await db.execute(sql`SELECT COALESCE(SUM(total_gross_minor),0)::bigint as gross,COALESCE(SUM(total_net_minor),0)::bigint as net,COALESCE(SUM(employee_count),0)::int as headcount FROM payroll.payroll_register WHERE tenant_id=${ctx.tenantId}::uuid AND period=${q.period2}`); return reply.send({period1:{period:q.period1,...(r1 as any)[0]},period2:{period:q.period2,...(r2 as any)[0]}}); });
}
