/**
 * legal-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as casesModule } from "../modules/cases/schema.js";
import { schema as hearingsModule } from "../modules/hearings/schema.js";
import { schema as noticesModule } from "../modules/notices/schema.js";
import { schema as contractsModule } from "../modules/contracts/schema.js";
import { schema as settlementsModule } from "../modules/settlements/schema.js";
import { schema as opinionsModule } from "../modules/opinions/schema.js";
import { schema as counselModule } from "../modules/counsel/schema.js";
import { schema as filingsModule } from "../modules/filings/schema.js";
import { schema as remindersModule } from "../modules/reminders/schema.js";
import { syncSchema } from "../modules/ecourts/sync-schema.js";
import { schema as documentsModule } from "../modules/documents/schema.js";
import { schema as limitationsModule } from "../modules/limitations/schema.js";
import { schema as boardIntakeModule } from "../modules/board-intake/schema.js";
import { schema as rtiModule } from "../modules/rti/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...casesModule,
  ...hearingsModule,
  ...noticesModule,
  ...contractsModule,
  ...settlementsModule,
  ...opinionsModule,
  ...counselModule,
  ...filingsModule,
  ...remindersModule,
  ...syncSchema,
  ...documentsModule,
  ...limitationsModule,
  ...boardIntakeModule,
  ...rtiModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
