import type { Queue } from "@civitasone/queue";
import { registerF3_ai_fraud_Consumers } from "./ai-fraud/f3-consumer.js";
import { registerF3_apar_Consumers } from "./apar/f3-consumer.js";
import { registerF3_appraisals_Consumers } from "./appraisals/f3-consumer.js";
import { registerF3_apprentice_stipend_Consumers } from "./apprentice-stipend/f3-consumer.js";
import { registerF3_assessment_Consumers } from "./assessment/f3-consumer.js";
import { registerF3_board_intake_Consumers } from "./board-intake/f3-consumer.js";
import { registerF3_claims_Consumers } from "./claims/f3-consumer.js";
import { registerF3_competency_Consumers } from "./competency/f3-consumer.js";
import { registerF3_consultant_invoice_Consumers } from "./consultant-invoice/f3-consumer.js";
import { registerF3_contractor_bill_Consumers } from "./contractor-bill/f3-consumer.js";
import { registerF3_contracts_Consumers } from "./contracts/f3-consumer.js";
import { registerF3_cpf_Consumers } from "./cpf/f3-consumer.js";
import { registerF3_deputation_Consumers } from "./deputation/f3-consumer.js";
import { registerF3_disciplinary_Consumers } from "./disciplinary/f3-consumer.js";
import { registerF3_employee_Consumers } from "./employee/f3-consumer.js";
import { registerF3_face_verification_Consumers } from "./face-verification/f3-consumer.js";
import { registerF3_geo_attendance_Consumers } from "./geo-attendance/f3-consumer.js";
import { registerF3_gpf_Consumers } from "./gpf/f3-consumer.js";
import { registerF3_holidays_Consumers } from "./holidays/f3-consumer.js";
import { registerF3_learning_Consumers } from "./learning/f3-consumer.js";
import { registerF3_leave_Consumers } from "./leave/f3-consumer.js";
import { registerF3_lifecycle_Consumers } from "./lifecycle/f3-consumer.js";
import { registerF3_manpower_planning_Consumers } from "./manpower-planning/f3-consumer.js";
import { registerF3_nps_Consumers } from "./nps/f3-consumer.js";
import { registerF3_pay_matrix_Consumers } from "./pay-matrix/f3-consumer.js";
import { registerF3_pension_Consumers } from "./pension/f3-consumer.js";
import { registerF3_recruitment_Consumers } from "./recruitment/f3-consumer.js";
import { registerF3_reservation_Consumers } from "./reservation/f3-consumer.js";
import { registerF3_rti_Consumers } from "./rti/f3-consumer.js";
import { registerF3_service_book_Consumers } from "./service-book/f3-consumer.js";
import { registerF3_training_admin_Consumers } from "./training-admin/f3-consumer.js";
export function registerF3LeftoverAll(queue: Queue): void {
  registerF3_ai_fraud_Consumers(queue);
  registerF3_apar_Consumers(queue);
  registerF3_appraisals_Consumers(queue);
  registerF3_apprentice_stipend_Consumers(queue);
  registerF3_assessment_Consumers(queue);
  registerF3_board_intake_Consumers(queue);
  registerF3_claims_Consumers(queue);
  registerF3_competency_Consumers(queue);
  registerF3_consultant_invoice_Consumers(queue);
  registerF3_contractor_bill_Consumers(queue);
  registerF3_contracts_Consumers(queue);
  registerF3_cpf_Consumers(queue);
  registerF3_deputation_Consumers(queue);
  registerF3_disciplinary_Consumers(queue);
  registerF3_employee_Consumers(queue);
  registerF3_face_verification_Consumers(queue);
  registerF3_geo_attendance_Consumers(queue);
  registerF3_gpf_Consumers(queue);
  registerF3_holidays_Consumers(queue);
  registerF3_learning_Consumers(queue);
  registerF3_leave_Consumers(queue);
  registerF3_lifecycle_Consumers(queue);
  registerF3_manpower_planning_Consumers(queue);
  registerF3_nps_Consumers(queue);
  registerF3_pay_matrix_Consumers(queue);
  registerF3_pension_Consumers(queue);
  registerF3_recruitment_Consumers(queue);
  registerF3_reservation_Consumers(queue);
  registerF3_rti_Consumers(queue);
  registerF3_service_book_Consumers(queue);
  registerF3_training_admin_Consumers(queue);
}
