-- Migration 0008: Close all HR gaps — UAN, recruitment pipeline, internship/apprenticeship

-- ═══ Add UAN + ESI number to employee ═══
ALTER TABLE employee.hrms_employees
  ADD COLUMN IF NOT EXISTS uan_number VARCHAR(12),
  ADD COLUMN IF NOT EXISTS esi_number VARCHAR(17),
  ADD COLUMN IF NOT EXISTS employee_category VARCHAR(32) NOT NULL DEFAULT 'regular'
    CHECK (employee_category IN ('regular', 'intern', 'apprentice', 'contractual', 'vendor_deputed', 'consultant'));

-- ═══ Interview Scheduling & Panel ═══
CREATE TABLE IF NOT EXISTS recruitment.hrms_interviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  application_id UUID NOT NULL,
  job_opening_id UUID NOT NULL,
  round_number INT NOT NULL DEFAULT 1,
  round_type VARCHAR(32) NOT NULL DEFAULT 'technical' CHECK (round_type IN ('screening', 'technical', 'hr', 'panel', 'final', 'group_discussion')),
  scheduled_date DATE NOT NULL,
  scheduled_time VARCHAR(5) NOT NULL, -- HH:MM
  duration_minutes INT NOT NULL DEFAULT 60,
  mode VARCHAR(16) NOT NULL DEFAULT 'in_person' CHECK (mode IN ('in_person', 'video', 'telephonic')),
  location VARCHAR(512),
  meeting_link VARCHAR(1024),
  panel_members JSONB NOT NULL DEFAULT '[]', -- [{id, name, role}]
  scorecard JSONB, -- {criteria: [{name, maxScore, givenScore}], overallScore, recommendation}
  status VARCHAR(24) NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled', 'no_show')),
  feedback TEXT,
  recommendation VARCHAR(24) CHECK (recommendation IN ('strong_hire', 'hire', 'maybe', 'no_hire', NULL)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL,
  version INT NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_interviews_app ON recruitment.hrms_interviews(tenant_id, application_id);
CREATE INDEX IF NOT EXISTS idx_interviews_job ON recruitment.hrms_interviews(tenant_id, job_opening_id, scheduled_date);

-- ═══ Enhance job_openings with publish workflow + category ═══
ALTER TABLE recruitment.hrms_job_openings
  ADD COLUMN IF NOT EXISTS category VARCHAR(32) NOT NULL DEFAULT 'regular'
    CHECK (category IN ('regular', 'intern', 'apprentice', 'contractual', 'deputation', 'consultant')),
  ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS min_experience_years INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_experience_years INT,
  ADD COLUMN IF NOT EXISTS qualification_required TEXT,
  ADD COLUMN IF NOT EXISTS salary_range_min_minor BIGINT,
  ADD COLUMN IF NOT EXISTS salary_range_max_minor BIGINT,
  ADD COLUMN IF NOT EXISTS location_id UUID,
  ADD COLUMN IF NOT EXISTS application_deadline DATE;

-- ═══ Enhance applications with interview stage tracking ═══
ALTER TABLE recruitment.hrms_applications
  ADD COLUMN IF NOT EXISTS current_round INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_score NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS final_recommendation VARCHAR(24);

-- ═══ Salary Slip Template Configuration ═══
CREATE TABLE IF NOT EXISTS payroll.payroll_slip_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  name VARCHAR(256) NOT NULL,
  template_html TEXT NOT NULL, -- Handlebars/Mustache template
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  header_logo_key VARCHAR(1024),
  footer_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID NOT NULL
);

-- Seed default salary slip template
INSERT INTO payroll.payroll_slip_templates (tenant_id, name, template_html, is_default, footer_text, created_by) VALUES (
  '00000000-0000-0000-0000-000000000001',
  'Standard Government Salary Slip',
  '<div class="slip">
  <header><h1>{{orgName}}</h1><h2>Pay Slip for {{month}}</h2></header>
  <table class="emp-info">
    <tr><td>Employee No</td><td>{{employeeNo}}</td><td>Name</td><td>{{employeeName}}</td></tr>
    <tr><td>Department</td><td>{{department}}</td><td>Designation</td><td>{{designation}}</td></tr>
    <tr><td>UAN</td><td>{{uan}}</td><td>PAN</td><td>{{pan}}</td></tr>
    <tr><td>Bank A/C</td><td>{{bankAccount}}</td><td>IFSC</td><td>{{bankIfsc}}</td></tr>
  </table>
  <table class="components">
    <thead><tr><th>Earnings</th><th>Amount</th><th>Deductions</th><th>Amount</th></tr></thead>
    <tbody>
      {{#each earnings}}<tr><td>{{name}}</td><td>₹{{amount}}</td><td>{{../deductions.[index].name}}</td><td>₹{{../deductions.[index].amount}}</td></tr>{{/each}}
    </tbody>
    <tfoot>
      <tr><td><b>Gross</b></td><td><b>₹{{grossPay}}</b></td><td><b>Total Deductions</b></td><td><b>₹{{totalDeductions}}</b></td></tr>
      <tr><td colspan="2"><b>Net Pay: ₹{{netPay}}</b></td><td colspan="2"><b>PF (Employee): ₹{{pfEmployee}} | PF (Employer): ₹{{pfEmployer}}</b></td></tr>
    </tfoot>
  </table>
  <footer><p>{{footerText}}</p><p>This is a computer-generated slip.</p></footer>
</div>',
  true,
  'Generated by CivitasOne HRMS. For queries contact HR department.',
  '00000000-0000-0000-0000-000000000099'
) ON CONFLICT DO NOTHING;

