-- 0156_medical_claim_no.sql
--
-- GAP-HR-MEDICAL-04: Claim Ref shown on /hr/medical was "MED/" + the first
-- 8 hex characters of the row's randomUUID() id -- not a stored claim
-- number. 32 bits of a v4 UUID can collide across two claims, and the
-- reference is not resolvable server-side (there was no column to search
-- against, only a client-side slice of an opaque id).
--
-- Fix: a real, DB-guaranteed-unique, sequential claim_no column, backed by
-- a plain per-table IDENTITY sequence. INTEGER, not BIGINT: this repo's
-- postgres-js/drizzle stack returns int8 columns as strings (JS bigint-
-- precision safety), which would force every caller (routes.ts, the web
-- app, this migration's own tests) to explicitly Number()-convert a value
-- that's really just a plain sequential counter with no realistic path to
-- 2^31 rows for one table. int4 avoids that footgun entirely and still
-- leaves ~2.1 billion headroom. This is a *global* sequence, not a
-- per-tenant/per-financial-year one --
-- deliberately simpler than the catalog's own suggested "tenant/FY
-- sequence" design: the actual bug this closes is collision + unsearchability,
-- not FY-scoped renumbering, and no other numbered reference in this schema
-- (e.g. disciplinary.hrms_disciplinary_cases.case_no) resets per tenant or
-- per year either -- it's simply a caller-supplied string there. A real
-- FY-reset requirement, if one exists, needs its own decision (numbering
-- format, what happens at FY rollover) and is better done as a dedicated,
-- separately-reviewed follow-up than guessed at here.
--
-- Existing rows: backfilled by claim_no's own IDENTITY sequence, ordered by
-- created_at so older claims get lower numbers (matches the "sequential"
-- expectation even though these weren't numbered at creation time).

-- GENERATED BY DEFAULT (not ALWAYS): the backfill UPDATE below needs to set
-- an explicit value per existing row, and Postgres has no override syntax
-- for UPDATE on a GENERATED ALWAYS identity column (only INSERT has
-- OVERRIDING SYSTEM VALUE) -- confirmed by testing ALWAYS against this
-- exact migration first ("column claim_no can only be updated to DEFAULT").
-- BY DEFAULT still self-assigns from the sequence on every real INSERT
-- (the application never references this column on write), it just also
-- permits this one-time backfill to set historical values explicitly.
ALTER TABLE medical.hrms_medical_claims
  ADD COLUMN IF NOT EXISTS claim_no INTEGER GENERATED BY DEFAULT AS IDENTITY;

-- Backfill existing rows in created_at order. The IDENTITY column above
-- already assigned every existing row a value in insertion (physical row)
-- order, not created_at order -- for a freshly-migrated table these
-- usually coincide, but re-sequencing explicitly by created_at is cheap
-- and removes the assumption.
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS rn
  FROM medical.hrms_medical_claims
)
UPDATE medical.hrms_medical_claims c
SET claim_no = ordered.rn
FROM ordered
WHERE c.id = ordered.id;

-- Keep the sequence itself ahead of the highest backfilled value so the
-- next real INSERT (which lets the IDENTITY column self-assign) can never
-- collide with a value the backfill above just wrote.
SELECT setval(
  pg_get_serial_sequence('medical.hrms_medical_claims', 'claim_no'),
  GREATEST(1, COALESCE((SELECT MAX(claim_no) FROM medical.hrms_medical_claims), 0)),
  true
);

ALTER TABLE medical.hrms_medical_claims
  ALTER COLUMN claim_no SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS hrms_medical_claims_claim_no_key
  ON medical.hrms_medical_claims (claim_no);
