/**
 * NO CONSUMER BY DESIGN (audit/status) - fire-and-forget facts.
 *
 * Owner decision 2026-10-07 (PR #1929): 247 audit/status/lifecycle events are
 * emitted for the audit trail and status history of their own service and have no
 * business consumer by design. Each entry was re-verified as emitted (not in
 * unemittedEvents) and as a lifecycle/audit fact, not a missing integration.
 * Anything implying a downstream effect (payment, ledger, notification delivery,
 * dispatch) is NOT here: it is tracked debt in known-defects.json and listed in
 * docs/ORPHAN-EVENTS-FOLLOWUP.md.
 */
export const NO_CONSUMER_CATEGORY = "NO CONSUMER BY DESIGN (audit/status)";
export const NO_CONSUMER_DECISION_REF = "owner decision 2026-10-07 (PR #1929)";

function nc(purpose: string): string {
  return `${NO_CONSUMER_CATEGORY} — 2026-10-07 — ${purpose}; no business consumer expected — ${NO_CONSUMER_DECISION_REF}`;
}

export const NO_CONSUMER_BY_DESIGN: Record<string, string> = {
  "admin.tenant.reactivated": nc("tenant reactivated audit/status fact in the admin lifecycle history"),
  "advertisement.application.created": nc("application created audit/status fact in the advertisement lifecycle history"),
  "advertisement.application.decided": nc("application decided audit/status fact in the advertisement lifecycle history"),
  "advertisement.application.submitted": nc("application submitted audit/status fact in the advertisement lifecycle history"),
  "advertisement.permit.cancelled": nc("permit cancelled audit/status fact in the advertisement lifecycle history"),
  "advertisement.permit.issued": nc("permit issued audit/status fact in the advertisement lifecycle history"),
  "advertisement.permit.renewed": nc("permit renewed audit/status fact in the advertisement lifecycle history"),
  "advertisement.permit.suspended": nc("permit suspended audit/status fact in the advertisement lifecycle history"),
  "advertisement.scrutiny.completed": nc("scrutiny completed audit/status fact in the advertisement lifecycle history"),
  "advertisement.scrutiny.initiated": nc("scrutiny initiated audit/status fact in the advertisement lifecycle history"),
  "advertisement.violation.notice_issued": nc("violation notice issued audit/status fact in the advertisement lifecycle history"),
  "advertisement.violation.penalty_imposed": nc("violation penalty imposed audit/status fact in the advertisement lifecycle history"),
  "advertisement.violation.removal_ordered": nc("violation removal ordered audit/status fact in the advertisement lifecycle history"),
  "advertisement.violation.removal_recorded": nc("violation removal recorded audit/status fact in the advertisement lifecycle history"),
  "advertisement.violation.reported": nc("violation reported audit/status fact in the advertisement lifecycle history"),
  "analytics.dashboard.deleted": nc("dashboard deleted audit/status fact in the analytics lifecycle history"),
  "animal.complaint.action_taken": nc("complaint action taken audit/status fact in the animal lifecycle history"),
  "animal.complaint.assigned": nc("complaint assigned audit/status fact in the animal lifecycle history"),
  "animal.complaint.closed": nc("complaint closed audit/status fact in the animal lifecycle history"),
  "animal.complaint.dispatched": nc("complaint dispatched audit/status fact in the animal lifecycle history"),
  "animal.complaint.reported": nc("complaint reported audit/status fact in the animal lifecycle history"),
  "animal.operation.recorded": nc("operation recorded audit/status fact in the animal lifecycle history"),
  "animal.registration.created": nc("registration created audit/status fact in the animal lifecycle history"),
  "animal.registration.renewed": nc("registration renewed audit/status fact in the animal lifecycle history"),
  "animal.registration.transferred": nc("registration transferred audit/status fact in the animal lifecycle history"),
  "building.application.created": nc("application created audit/status fact in the building lifecycle history"),
  "building.application.decided": nc("application decided audit/status fact in the building lifecycle history"),
  "building.application.submitted": nc("application submitted audit/status fact in the building lifecycle history"),
  "building.application.withdrawn": nc("application withdrawn audit/status fact in the building lifecycle history"),
  "building.certificate.issued": nc("certificate issued audit/status fact in the building lifecycle history"),
  "building.permit.cancelled": nc("permit cancelled audit/status fact in the building lifecycle history"),
  "building.permit.issued": nc("permit issued audit/status fact in the building lifecycle history"),
  "building.permit.restored": nc("permit restored audit/status fact in the building lifecycle history"),
  "building.permit.suspended": nc("permit suspended audit/status fact in the building lifecycle history"),
  "building.renewal.decided": nc("renewal decided audit/status fact in the building lifecycle history"),
  "building.renewal.requested": nc("renewal requested audit/status fact in the building lifecycle history"),
  "building.scrutiny.completed": nc("scrutiny completed audit/status fact in the building lifecycle history"),
  "building.scrutiny.initiated": nc("scrutiny initiated audit/status fact in the building lifecycle history"),
  "crematorium.booking.cancelled": nc("booking cancelled audit/status fact in the crematorium lifecycle history"),
  "crematorium.booking.completed": nc("booking completed audit/status fact in the crematorium lifecycle history"),
  "crematorium.booking.confirmed": nc("booking confirmed audit/status fact in the crematorium lifecycle history"),
  "crematorium.booking.requested": nc("booking requested audit/status fact in the crematorium lifecycle history"),
  "crematorium.facility.created": nc("facility created audit/status fact in the crematorium lifecycle history"),
  "crematorium.facility.updated": nc("facility updated audit/status fact in the crematorium lifecycle history"),
  "crematorium.record.created": nc("record created audit/status fact in the crematorium lifecycle history"),
  "crm.account.updated": nc("account updated audit/status fact in the crm lifecycle history"),
  "crm.campaign.approved": nc("campaign approved audit/status fact in the crm lifecycle history"),
  "crm.campaign.rejected": nc("campaign rejected audit/status fact in the crm lifecycle history"),
  "crm.campaign.submitted_for_approval": nc("campaign submitted for approval audit/status fact in the crm lifecycle history"),
  "crm.citizen_feedback.recorded": nc("citizen feedback recorded audit/status fact in the crm lifecycle history"),
  "crm.rti.disposed": nc("rti disposed audit/status fact in the crm lifecycle history"),
  "crm.rti.first_appeal_decided": nc("rti first appeal decided audit/status fact in the crm lifecycle history"),
  "crm.rti.second_appeal_recorded": nc("rti second appeal recorded audit/status fact in the crm lifecycle history"),
  "document.bulkscan.batch.cancelled": nc("bulkscan batch cancelled audit/status fact in the document lifecycle history"),
  "document.bulkscan.batch.completed": nc("bulkscan batch completed audit/status fact in the document lifecycle history"),
  "document.bulkscan.batch.created": nc("bulkscan batch created audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.extracted": nc("bulkscan file extracted audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.failed": nc("bulkscan file failed audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.filed": nc("bulkscan file filed audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.quarantined": nc("bulkscan file quarantined audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.retention_deleted": nc("bulkscan file retention deleted audit/status fact in the document lifecycle history"),
  "document.bulkscan.file.returned_to_review": nc("bulkscan file returned to review audit/status fact in the document lifecycle history"),
  "document.bulkscan.link.linked": nc("bulkscan link linked audit/status fact in the document lifecycle history"),
  "document.bulkscan.link.requested": nc("bulkscan link requested audit/status fact in the document lifecycle history"),
  "document.bulkscan.link.unlinked": nc("bulkscan link unlinked audit/status fact in the document lifecycle history"),
  "document.bulkscan.settings.change_requested": nc("bulkscan settings change requested audit/status fact in the document lifecycle history"),
  "document.bulkscan.settings.changed": nc("bulkscan settings changed audit/status fact in the document lifecycle history"),
  "document.dak.acknowledged": nc("dak acknowledged audit/status fact in the document lifecycle history"),
  "document.dak.created": nc("dak created audit/status fact in the document lifecycle history"),
  "document.dak.forwarded": nc("dak forwarded audit/status fact in the document lifecycle history"),
  "document.file.deleted": nc("file deleted audit/status fact in the document lifecycle history"),
  "document.file.moved": nc("file moved audit/status fact in the document lifecycle history"),
  "document.file.uploaded": nc("file uploaded audit/status fact in the document lifecycle history"),
  "document.folder.created": nc("folder created audit/status fact in the document lifecycle history"),
  "drainage.complaint.assigned": nc("complaint assigned audit/status fact in the drainage lifecycle history"),
  "drainage.complaint.closed": nc("complaint closed audit/status fact in the drainage lifecycle history"),
  "drainage.complaint.created": nc("complaint created audit/status fact in the drainage lifecycle history"),
  "drainage.complaint.resolved": nc("complaint resolved audit/status fact in the drainage lifecycle history"),
  "drainage.field_action.created": nc("field action created audit/status fact in the drainage lifecycle history"),
  "drainage.hotspot.identified": nc("hotspot identified audit/status fact in the drainage lifecycle history"),
  "drainage.hotspot.resolved": nc("hotspot resolved audit/status fact in the drainage lifecycle history"),
  "drainage.hotspot.status_updated": nc("hotspot status updated audit/status fact in the drainage lifecycle history"),
  "event.application.created": nc("application created audit/status fact in the event lifecycle history"),
  "event.application.submitted": nc("application submitted audit/status fact in the event lifecycle history"),
  "event.application.withdrawn": nc("application withdrawn audit/status fact in the event lifecycle history"),
  "event.noc.requested": nc("noc requested audit/status fact in the event lifecycle history"),
  "event.noc.responded": nc("noc responded audit/status fact in the event lifecycle history"),
  "event.permit.issued": nc("permit issued audit/status fact in the event lifecycle history"),
  "event.permit.revoked": nc("permit revoked audit/status fact in the event lifecycle history"),
  "event.post_inspection.conducted": nc("post inspection conducted audit/status fact in the event lifecycle history"),
  "fire.application.created": nc("application created audit/status fact in the fire lifecycle history"),
  "fire.application.submitted": nc("application submitted audit/status fact in the fire lifecycle history"),
  "fire.application.withdrawn": nc("application withdrawn audit/status fact in the fire lifecycle history"),
  "fire.inspection.completed": nc("inspection completed audit/status fact in the fire lifecycle history"),
  "fire.inspection.findings_recorded": nc("inspection findings recorded audit/status fact in the fire lifecycle history"),
  "fire.inspection.scheduled": nc("inspection scheduled audit/status fact in the fire lifecycle history"),
  "fire.noc.issued": nc("noc issued audit/status fact in the fire lifecycle history"),
  "fire.noc.revoked": nc("noc revoked audit/status fact in the fire lifecycle history"),
  "fire.noc.suspended": nc("noc suspended audit/status fact in the fire lifecycle history"),
  "fire.renewal.decided": nc("renewal decided audit/status fact in the fire lifecycle history"),
  "fire.renewal.requested": nc("renewal requested audit/status fact in the fire lifecycle history"),
  "grant.application.withdrawn": nc("application withdrawn audit/status fact in the grant lifecycle history"),
  "grant.scheme.closed": nc("scheme closed audit/status fact in the grant lifecycle history"),
  "grant.scheme.updated": nc("scheme updated audit/status fact in the grant lifecycle history"),
  "hrms.attendance.regularisation.approved": nc("attendance regularisation approved audit/status fact in the hrms lifecycle history"),
  "hrms.attendance.regularisation.rejected": nc("attendance regularisation rejected audit/status fact in the hrms lifecycle history"),
  "inspection.capa.started": nc("capa started audit/status fact in the inspection lifecycle history"),
  "inventory.bin.status_changed": nc("bin status changed audit/status fact in the inventory lifecycle history"),
  "inventory.item.linked": nc("item linked audit/status fact in the inventory lifecycle history"),
  "inventory.item.unlinked": nc("item unlinked audit/status fact in the inventory lifecycle history"),
  "inventory.settings.updated": nc("settings updated audit/status fact in the inventory lifecycle history"),
  "inventory.srn.created": nc("srn created audit/status fact in the inventory lifecycle history"),
  "knowledge.policy.rejected": nc("policy rejected audit/status fact in the knowledge lifecycle history"),
  "location.location.updated": nc("location updated audit/status fact in the location lifecycle history"),
  "market.allotment.agreement_signed": nc("allotment agreement signed audit/status fact in the market lifecycle history"),
  "market.allotment.applied": nc("allotment applied audit/status fact in the market lifecycle history"),
  "market.allotment.selected": nc("allotment selected audit/status fact in the market lifecycle history"),
  "market.lifecycle.approved": nc("lifecycle approved audit/status fact in the market lifecycle history"),
  "market.lifecycle.cancellation_requested": nc("lifecycle cancellation requested audit/status fact in the market lifecycle history"),
  "market.lifecycle.completed": nc("lifecycle completed audit/status fact in the market lifecycle history"),
  "market.lifecycle.eviction_initiated": nc("lifecycle eviction initiated audit/status fact in the market lifecycle history"),
  "market.lifecycle.rejected": nc("lifecycle rejected audit/status fact in the market lifecycle history"),
  "market.lifecycle.transfer_requested": nc("lifecycle transfer requested audit/status fact in the market lifecycle history"),
  "market.property.created": nc("property created audit/status fact in the market lifecycle history"),
  "market.property.updated": nc("property updated audit/status fact in the market lifecycle history"),
  "parking.booking.cancelled": nc("booking cancelled audit/status fact in the parking lifecycle history"),
  "parking.booking.created": nc("booking created audit/status fact in the parking lifecycle history"),
  "parking.booking.entry_recorded": nc("booking entry recorded audit/status fact in the parking lifecycle history"),
  "parking.booking.exit_recorded": nc("booking exit recorded audit/status fact in the parking lifecycle history"),
  "parking.facility.created": nc("facility created audit/status fact in the parking lifecycle history"),
  "parking.facility.updated": nc("facility updated audit/status fact in the parking lifecycle history"),
  "parking.pass.cancelled": nc("pass cancelled audit/status fact in the parking lifecycle history"),
  "parking.pass.created": nc("pass created audit/status fact in the parking lifecycle history"),
  "parking.violation.contested": nc("violation contested audit/status fact in the parking lifecycle history"),
  "parking.violation.issued": nc("violation issued audit/status fact in the parking lifecycle history"),
  "parks.asset.created": nc("asset created audit/status fact in the parks lifecycle history"),
  "parks.asset.maintenance_recorded": nc("asset maintenance recorded audit/status fact in the parks lifecycle history"),
  "parks.asset.updated": nc("asset updated audit/status fact in the parks lifecycle history"),
  "parks.complaint.assigned": nc("complaint assigned audit/status fact in the parks lifecycle history"),
  "parks.complaint.closed": nc("complaint closed audit/status fact in the parks lifecycle history"),
  "parks.complaint.created": nc("complaint created audit/status fact in the parks lifecycle history"),
  "parks.complaint.resolved": nc("complaint resolved audit/status fact in the parks lifecycle history"),
  "parks.inspection.completed": nc("inspection completed audit/status fact in the parks lifecycle history"),
  "parks.inspection.scheduled": nc("inspection scheduled audit/status fact in the parks lifecycle history"),
  "parks.tree_request.approved": nc("tree request approved audit/status fact in the parks lifecycle history"),
  "parks.tree_request.completed": nc("tree request completed audit/status fact in the parks lifecycle history"),
  "parks.tree_request.created": nc("tree request created audit/status fact in the parks lifecycle history"),
  "parks.tree_request.inspected": nc("tree request inspected audit/status fact in the parks lifecycle history"),
  "parks.tree_request.rejected": nc("tree request rejected audit/status fact in the parks lifecycle history"),
  "payroll.bank_file_signing.updated": nc("bank file signing updated audit/status fact in the payroll lifecycle history"),
  "payroll.costing_rule.updated": nc("costing rule updated audit/status fact in the payroll lifecycle history"),
  "payroll.letterhead.upserted": nc("letterhead upserted audit/status fact in the payroll lifecycle history"),
  "payroll.pt_version.created": nc("pt version created audit/status fact in the payroll lifecycle history"),
  "payroll.settings.updated": nc("settings updated audit/status fact in the payroll lifecycle history"),
  "procurement.rfq.closed": nc("rfq closed audit/status fact in the procurement lifecycle history"),
  "refund.approval.approved": nc("approval approved audit/status fact in the refund lifecycle history"),
  "refund.approval.rejected": nc("approval rejected audit/status fact in the refund lifecycle history"),
  "refund.approval.returned": nc("approval returned audit/status fact in the refund lifecycle history"),
  "refund.request.created": nc("request created audit/status fact in the refund lifecycle history"),
  "refund.request.reviewed": nc("request reviewed audit/status fact in the refund lifecycle history"),
  "refund.request.submitted": nc("request submitted audit/status fact in the refund lifecycle history"),
  "refund.request.withdrawn": nc("request withdrawn audit/status fact in the refund lifecycle history"),
  "roadcut.application.approved": nc("application approved audit/status fact in the roadcut lifecycle history"),
  "roadcut.application.created": nc("application created audit/status fact in the roadcut lifecycle history"),
  "roadcut.application.rejected": nc("application rejected audit/status fact in the roadcut lifecycle history"),
  "roadcut.application.submitted": nc("application submitted audit/status fact in the roadcut lifecycle history"),
  "roadcut.application.under_review": nc("application under review audit/status fact in the roadcut lifecycle history"),
  "roadcut.application.withdrawn": nc("application withdrawn audit/status fact in the roadcut lifecycle history"),
  "roadcut.inspection.completed": nc("inspection completed audit/status fact in the roadcut lifecycle history"),
  "roadcut.inspection.scheduled": nc("inspection scheduled audit/status fact in the roadcut lifecycle history"),
  "roadcut.permit.cancelled": nc("permit cancelled audit/status fact in the roadcut lifecycle history"),
  "roadcut.permit.completed": nc("permit completed audit/status fact in the roadcut lifecycle history"),
  "roadcut.permit.extended": nc("permit extended audit/status fact in the roadcut lifecycle history"),
  "roadcut.permit.issued": nc("permit issued audit/status fact in the roadcut lifecycle history"),
  "roadcut.restoration.completed": nc("restoration completed audit/status fact in the roadcut lifecycle history"),
  "roadcut.restoration.started": nc("restoration started audit/status fact in the roadcut lifecycle history"),
  "sewerage.complaint.assigned": nc("complaint assigned audit/status fact in the sewerage lifecycle history"),
  "sewerage.complaint.closed": nc("complaint closed audit/status fact in the sewerage lifecycle history"),
  "sewerage.complaint.created": nc("complaint created audit/status fact in the sewerage lifecycle history"),
  "sewerage.complaint.resolved": nc("complaint resolved audit/status fact in the sewerage lifecycle history"),
  "sewerage.connection.activated": nc("connection activated audit/status fact in the sewerage lifecycle history"),
  "sewerage.connection.applied": nc("connection applied audit/status fact in the sewerage lifecycle history"),
  "sewerage.connection.status_updated": nc("connection status updated audit/status fact in the sewerage lifecycle history"),
  "sewerage.desludging.booked": nc("desludging booked audit/status fact in the sewerage lifecycle history"),
  "sewerage.desludging.cancelled": nc("desludging cancelled audit/status fact in the sewerage lifecycle history"),
  "sewerage.desludging.completed": nc("desludging completed audit/status fact in the sewerage lifecycle history"),
  "sewerage.desludging.dispatched": nc("desludging dispatched audit/status fact in the sewerage lifecycle history"),
  "sewerage.desludging.scheduled": nc("desludging scheduled audit/status fact in the sewerage lifecycle history"),
  "sewerage.field_record.created": nc("field record created audit/status fact in the sewerage lifecycle history"),
  "shop.application.created": nc("application created audit/status fact in the shop lifecycle history"),
  "shop.application.decided": nc("application decided audit/status fact in the shop lifecycle history"),
  "shop.application.submitted": nc("application submitted audit/status fact in the shop lifecycle history"),
  "shop.application.withdrawn": nc("application withdrawn audit/status fact in the shop lifecycle history"),
  "shop.permit.cancelled": nc("permit cancelled audit/status fact in the shop lifecycle history"),
  "shop.permit.issued": nc("permit issued audit/status fact in the shop lifecycle history"),
  "shop.permit.notice_issued": nc("permit notice issued audit/status fact in the shop lifecycle history"),
  "shop.permit.restored": nc("permit restored audit/status fact in the shop lifecycle history"),
  "shop.permit.suspended": nc("permit suspended audit/status fact in the shop lifecycle history"),
  "shop.renewal.decided": nc("renewal decided audit/status fact in the shop lifecycle history"),
  "shop.renewal.requested": nc("renewal requested audit/status fact in the shop lifecycle history"),
  "shop.scrutiny.completed": nc("scrutiny completed audit/status fact in the shop lifecycle history"),
  "shop.scrutiny.initiated": nc("scrutiny initiated audit/status fact in the shop lifecycle history"),
  "swm.bulk_generator.registered": nc("bulk generator registered audit/status fact in the swm lifecycle history"),
  "swm.bulk_generator.suspended": nc("bulk generator suspended audit/status fact in the swm lifecycle history"),
  "swm.collection.cancelled": nc("collection cancelled audit/status fact in the swm lifecycle history"),
  "swm.collection.completed": nc("collection completed audit/status fact in the swm lifecycle history"),
  "swm.collection.requested": nc("collection requested audit/status fact in the swm lifecycle history"),
  "swm.collection.scheduled": nc("collection scheduled audit/status fact in the swm lifecycle history"),
  "swm.complaint.assigned": nc("complaint assigned audit/status fact in the swm lifecycle history"),
  "swm.complaint.closed": nc("complaint closed audit/status fact in the swm lifecycle history"),
  "swm.complaint.created": nc("complaint created audit/status fact in the swm lifecycle history"),
  "swm.complaint.resolved": nc("complaint resolved audit/status fact in the swm lifecycle history"),
  "swm.field_task.completed": nc("field task completed audit/status fact in the swm lifecycle history"),
  "swm.field_task.created": nc("field task created audit/status fact in the swm lifecycle history"),
  "swm.hotspot.identified": nc("hotspot identified audit/status fact in the swm lifecycle history"),
  "swm.hotspot.resolved": nc("hotspot resolved audit/status fact in the swm lifecycle history"),
  "trade.application.created": nc("application created audit/status fact in the trade lifecycle history"),
  "trade.application.decided": nc("application decided audit/status fact in the trade lifecycle history"),
  "trade.application.submitted": nc("application submitted audit/status fact in the trade lifecycle history"),
  "trade.application.withdrawn": nc("application withdrawn audit/status fact in the trade lifecycle history"),
  "trade.licence.cancelled": nc("licence cancelled audit/status fact in the trade lifecycle history"),
  "trade.licence.issued": nc("licence issued audit/status fact in the trade lifecycle history"),
  "trade.licence.notice_issued": nc("licence notice issued audit/status fact in the trade lifecycle history"),
  "trade.licence.restored": nc("licence restored audit/status fact in the trade lifecycle history"),
  "trade.licence.suspended": nc("licence suspended audit/status fact in the trade lifecycle history"),
  "trade.renewal.decided": nc("renewal decided audit/status fact in the trade lifecycle history"),
  "trade.renewal.requested": nc("renewal requested audit/status fact in the trade lifecycle history"),
  "trade.scrutiny.completed": nc("scrutiny completed audit/status fact in the trade lifecycle history"),
  "trade.scrutiny.initiated": nc("scrutiny initiated audit/status fact in the trade lifecycle history"),
  "vendor.cancellation.requested": nc("cancellation requested audit/status fact in the vendor lifecycle history"),
  "vendor.committee.assigned": nc("committee assigned audit/status fact in the vendor lifecycle history"),
  "vendor.committee.completed": nc("committee completed audit/status fact in the vendor lifecycle history"),
  "vendor.licence.cancelled": nc("licence cancelled audit/status fact in the vendor lifecycle history"),
  "vendor.licence.issued": nc("licence issued audit/status fact in the vendor lifecycle history"),
  "vendor.licence.suspended": nc("licence suspended audit/status fact in the vendor lifecycle history"),
  "vendor.registration.approved": nc("registration approved audit/status fact in the vendor lifecycle history"),
  "vendor.registration.created": nc("registration created audit/status fact in the vendor lifecycle history"),
  "vendor.registration.rejected": nc("registration rejected audit/status fact in the vendor lifecycle history"),
  "vendor.registration.submitted": nc("registration submitted audit/status fact in the vendor lifecycle history"),
  "vendor.registration.withdrawn": nc("registration withdrawn audit/status fact in the vendor lifecycle history"),
  "vendor.renewal.requested": nc("renewal requested audit/status fact in the vendor lifecycle history"),
  "vendor.surrender.requested": nc("surrender requested audit/status fact in the vendor lifecycle history"),
  "vendor.zone.allocated": nc("zone allocated audit/status fact in the vendor lifecycle history"),
  "vendor.zone_transfer.requested": nc("zone transfer requested audit/status fact in the vendor lifecycle history"),
  "visitor.blacklist.deactivated": nc("blacklist deactivated audit/status fact in the visitor lifecycle history"),
  "works.issue.closed": nc("issue closed audit/status fact in the works lifecycle history"),
  "works.master.updated": nc("master updated audit/status fact in the works lifecycle history"),
  "crm.grievance.appealed": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance appealed audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.grievance.assigned": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance assigned audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.grievance.closed": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance closed audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.grievance.forwarded": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance forwarded audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.grievance.registered": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance registered audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.grievance.resolved": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — grievance resolved audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.rti.created": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — rti created audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.rti.first_appealed": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — rti first appealed audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.rti.forwarded": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — rti forwarded audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.rti.responded": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — rti responded audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.service_request.created": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — service request created audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
  "crm.service_request.status_changed": `${NO_CONSUMER_CATEGORY} — 2026-10-08 — service request status changed audit/status fact in the crm lifecycle history (review-2 u07); no business consumer expected — ${NO_CONSUMER_DECISION_REF}`,
};
