/**
 * workflow-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as instancesModule } from "../modules/instances/schema.js";
import { schema as tasksModule } from "../modules/tasks/schema.js";
import { schema as definitionsModule } from "../modules/definitions/schema.js";
import { schema as historyModule } from "../modules/history/schema.js";
import { schema as delegationsModule } from "../modules/delegations/schema.js";
import { roleMembers, assignmentCursors } from "../modules/assignment/resolver.js";
import { schema as assignmentModule } from "../modules/assignment/schema.js";
import { consumerAttempts, deadLetters } from "../modules/dlq/repo.js";
import { outboxSchema } from "./outbox.js";
import { schema as messagesModule } from "../modules/messages/schema.js";
import { schema as decisionsModule } from "../modules/decisions/schema.js";
import { schema as forwardingModule } from "../modules/forwarding/schema.js";
import { schema as designerModule } from "../modules/designer/schema.js";
import { schema as dmnModule } from "../modules/dmn/schema.js";

const SCHEMA = {
  ...instancesModule,
  ...tasksModule,
  ...definitionsModule,
  ...historyModule,
  ...delegationsModule,
  ...assignmentModule,
  ...outboxSchema,
  ...messagesModule,
  ...decisionsModule,
  ...forwardingModule,
  ...designerModule,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
