/**
 * knowledge-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as documentsModule } from "../modules/documents/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...documentsModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

/**
 * scopedRead — wraps a read query in db.transaction() so PostgreSQL RLS policies
 * (tenant isolation via GUC) are enforced on the read path.
 */
export function scopedRead<T>(fn: (tx: typeof db) => Promise<T>): Promise<T> {
  return db.transaction(fn as never) as Promise<T>;
}

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
