/**
 * contract-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as contractsModule } from "../modules/contracts/schema.js";
import { schema as rateModule }      from "../modules/rate/schema.js";
import { schema as clausesModule }   from "../modules/clauses/schema.js";
import { schema as versionsModule }  from "../modules/versions/schema.js";
import { schema as obligationsModule } from "../modules/obligations/schema.js";
import { schema as renewalsModule }    from "../modules/renewals/schema.js";
import { schema as approvalsModule }   from "../modules/approvals/schema.js";
import { schema as esignModule }       from "../modules/esign/schema.js";
import { outboxSchema }              from "./outbox.js";

const SCHEMA = {
  ...contractsModule,
  ...rateModule,
  ...clausesModule,
  ...versionsModule,
  ...obligationsModule,
  ...renewalsModule,
  ...approvalsModule,
  ...esignModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
