/**
 * hrms-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { sql } from "drizzle-orm";
import { createTenantDb } from "@civitasone/db";
import { schema as employeeModule }    from "../modules/employee/schema.js";
import { schema as recruitmentModule } from "../modules/recruitment/schema.js";
import { schema as requisitionModule } from "../modules/recruitment/requisition-schema.js";
import { schema as candidateModule } from "../modules/recruitment/candidate-schema.js";
import { schema as candidateSkillsModule } from "../modules/recruitment/skills-schema.js";
import { schema as assessmentBlueprintModule } from "../modules/recruitment/blueprint-schema.js";
import { schema as assessmentAttemptModule } from "../modules/recruitment/attempt-schema.js";
import { schema as assessmentResultModule } from "../modules/recruitment/result-schema.js";
import { schema as selectionModule } from "../modules/recruitment/selection-schema.js";
import { schema as recruitmentReservationModule } from "../modules/recruitment/reservation-schema.js";
import { schema as qualificationModule } from "../modules/recruitment/qualification-schema.js";
import { schema as attendanceModule }  from "../modules/attendance/schema.js";
import { schema as leaveModule }       from "../modules/leave/schema.js";
import { schema as trainingModule }    from "../modules/training/schema.js";
import { schema as lifecycleModule }   from "../modules/lifecycle/schema.js";
import { schema as serviceBookModule } from "../modules/service-book/schema.js";
import { schema as appraisalModule }   from "../modules/appraisals/schema.js";
import { aparSchema as aparModule }            from "../modules/apar/schema.js";
import { gpfModuleSchema as gpfModule }        from "../modules/gpf/schema.js";
import { npsModuleSchema as npsModule }        from "../modules/nps/schema.js";
import { cpfModuleSchema as cpfModule }        from "../modules/cpf/schema.js";
import { schema as deputationModule }  from "../modules/deputation/schema.js";
import { schema as claimsModule }      from "../modules/claims/schema.js";
import { schema as schedulerModule }   from "../modules/scheduler/schema.js";
import { schema as disciplinaryModule } from "../modules/disciplinary/schema.js";
import { schema as reservationModule }  from "../modules/reservation/schema.js";
import { schema as medicalModule }      from "../modules/medical/schema.js";
import { schema as boardIntakeModule } from "../modules/board-intake/schema.js";
import { schema as assessmentModule } from "../modules/assessment/schema.js";
import { schema as trainingAdminModule } from "../modules/training-admin/schema.js";
import { schema as learningModule }      from "../modules/learning/schema.js";
import { schema as competencyModule }    from "../modules/competency/schema.js";
import { schema as contractsModule }    from "../modules/contracts/schema.js";
import { schema as manpowerModule }     from "../modules/manpower-planning/schema.js";
import { schema as consultantInvoiceModule } from "../modules/consultant-invoice/schema.js";
import { schema as contractorBillModule } from "../modules/contractor-bill/schema.js";
import { schema as apprenticeStipendModule } from "../modules/apprentice-stipend/schema.js";
import { schema as payrollConfigModule } from "../modules/payroll-config/schema.js";
import { schema as seniorityModule }    from "../modules/seniority/schema.js";
import { outboxSchema }                from "./outbox.js";

const SCHEMA = {
  ...employeeModule,
  ...recruitmentModule,
  ...requisitionModule,
  ...candidateModule,
  ...candidateSkillsModule,
  ...assessmentBlueprintModule,
  ...assessmentAttemptModule,
  ...assessmentResultModule,
  ...selectionModule,
  ...recruitmentReservationModule,
  ...qualificationModule,
  ...attendanceModule,
  ...leaveModule,
  ...trainingModule,
  ...lifecycleModule,
  ...serviceBookModule,
  ...appraisalModule,
  ...aparModule,
  ...gpfModule,
  ...npsModule,
  ...cpfModule,
  ...deputationModule,
  ...claimsModule,
  ...schedulerModule,
  ...disciplinaryModule,
  ...reservationModule,
  ...medicalModule,
  ...boardIntakeModule,
  ...assessmentModule,
  ...trainingAdminModule,
  ...learningModule,
  ...competencyModule,
  ...contractsModule,
  ...manpowerModule,
  ...consultantInvoiceModule,
  ...contractorBillModule,
  ...apprenticeStipendModule,
  ...payrollConfigModule,
  ...seniorityModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * node-postgres-style adapter over the postgres-js client.
 *
 * Several modules (social, device-trust, id-cards, visiting-cards, ai-ml) issue
 * raw parameterised SQL using the classic `pg` `query(text, params)` shape that
 * returns `{ rows, rowCount }`. postgres-js instead exposes a tagged-template
 * client (`sql\`...\``) plus `sql.unsafe(text, params)` which resolves to a
 * row-list array. This thin wrapper bridges the two so the existing raw-SQL
 * handlers keep their behaviour while remaining type-safe. Preserved verbatim
 * across the TenantRouter-adoption codemod — it wraps the pool-tier
 * `sqlClient` above, unchanged in shape/identity.
 */
export const sqlPool = {
  async query<T = any>(
    text: string,
    params: readonly unknown[] = [],
  ): Promise<{ rows: T[]; rowCount: number }> {
    const result = await sqlClient.unsafe(text, params as unknown as never[]);
    const rows = result as unknown as T[];
    const rowCount = (result as unknown as { count?: number }).count ?? rows.length;
    return { rows, rowCount };
  },
};

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain db.select() runs on a pooled connection with no
 * app.tenant_id GUC set, so under a NOBYPASSRLS role (hrms_svc / identity_svc)
 * the fail-closed policy returns ZERO rows. Wrapping the read in db.transaction
 * makes wrapWithTenantGuc set the GUC from AsyncLocalStorage - reads are then
 * correctly tenant-scoped by RLS, not merely by an app-layer WHERE. Mirrors
 * court-service / visitor-service / meeting-service.
 */
export type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<Db["transaction"]>[0]) as Promise<T>;
}

/**
 * Effective-dating scheduler fix (Bug 1 follow-up to migration 0144): run a
 * genuinely cross-tenant SELECT with the `app.platform_bypass` GUC set for
 * the transaction, per the additional permissive SELECT-only RLS policy
 * migration 0133_platform_bypass_read_policy.sql already added to
 * employee.hrms_employees (originally for
 * services/inventory-service/tests/data-quality.test.ts's DQ-HRMS-*
 * checks). Used by lifecycle/effective-scheduler.ts to discover the full
 * tenant universe before re-entering each tenant's own strict RLS context
 * via runWithTenant to look for that tenant's due promotions/transfers.
 *
 * Why this is needed instead of a SECURITY DEFINER function (migration
 * 0144's original approach for due_promotion_ids/due_transfer_ids): no role
 * in this fleet may bypass RLS, by design (see bootstrap-postgres.sh's "L3
 * lane" comment) — hrms_svc (this service's own connecting role, and the
 * role hrms-service's migrations actually run as, per that script's
 * SERVICE_DBS/needs_superuser routing) has no BYPASSRLS, and neither does
 * civitas_admin (bootstrap_admin_role.sql: NOSUPERUSER NOBYPASSRLS,
 * deliberately, so the "no %_svc role holds BYPASSRLS" assertion keeps
 * meaning something). A SECURITY DEFINER function only elevates to its
 * OWNER's privileges, and the owner here is hrms_svc either way, so it was
 * never actually bypassing anything — migration 0144's due_promotion_ids/
 * due_transfer_ids silently returned zero rows on every call, regardless of
 * SECURITY DEFINER. Mirrors admin-service's/audit-service's/
 * payroll-service's/inspection-service's identical scopedPlatformRead
 * pattern exactly (inspection-service's worker.ts processOverdueFindings is
 * the closest analog: platform-bypass read for tenant ids, then a
 * runWithTenant loop for the actual per-tenant work).
 *
 * SECURITY: this must ONLY be called from trusted server-side code with no
 * user-supplied input — never derived from a request header/param/JWT
 * claim. It is SELECT-only by policy design (migration 0133 added an
 * ADDITIONAL permissive SELECT policy; INSERT/UPDATE/DELETE on
 * hrms_employees remain governed solely by the strict tenant-match policy),
 * so this can never let a write skip tenant scoping.
 */
export function scopedPlatformRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(async (tx) => {
    await (tx as unknown as { execute: (q: unknown) => Promise<unknown> }).execute(
      sql`SELECT set_config('app.platform_bypass', 'true', true)`,
    );
    return fn(tx);
  }) as Promise<T>;
}
