/**
 * hrms-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as employeeModule }    from "../modules/employee/schema.js";
import { schema as recruitmentModule } from "../modules/recruitment/schema.js";
import { schema as attendanceModule }  from "../modules/attendance/schema.js";
import { schema as leaveModule }       from "../modules/leave/schema.js";
import { schema as trainingModule }    from "../modules/training/schema.js";
import { schema as lifecycleModule }   from "../modules/lifecycle/schema.js";
import { schema as serviceBookModule } from "../modules/service-book/schema.js";
import { schema as appraisalModule }   from "../modules/appraisals/schema.js";
import { aparSchema as aparModule }            from "../modules/apar/schema.js";
import { gpfModuleSchema as gpfModule }        from "../modules/gpf/schema.js";
import { npsModuleSchema as npsModule }        from "../modules/nps/schema.js";
import { cpfModuleSchema as cpfModule }        from "../modules/cpf/schema.js";
import { schema as deputationModule }  from "../modules/deputation/schema.js";
import { schema as claimsModule }      from "../modules/claims/schema.js";
import { schema as schedulerModule }   from "../modules/scheduler/schema.js";
import { schema as disciplinaryModule } from "../modules/disciplinary/schema.js";
import { schema as reservationModule }  from "../modules/reservation/schema.js";
import { schema as medicalModule }      from "../modules/medical/schema.js";
import { schema as boardIntakeModule } from "../modules/board-intake/schema.js";
import { schema as assessmentModule } from "../modules/assessment/schema.js";
import { schema as trainingAdminModule } from "../modules/training-admin/schema.js";
import { schema as learningModule }      from "../modules/learning/schema.js";
import { schema as competencyModule }    from "../modules/competency/schema.js";
import { schema as contractsModule }    from "../modules/contracts/schema.js";
import { schema as manpowerModule }     from "../modules/manpower-planning/schema.js";
import { schema as consultantInvoiceModule } from "../modules/consultant-invoice/schema.js";
import { schema as contractorBillModule } from "../modules/contractor-bill/schema.js";
import { outboxSchema }                from "./outbox.js";

const SCHEMA = {
  ...employeeModule,
  ...recruitmentModule,
  ...attendanceModule,
  ...leaveModule,
  ...trainingModule,
  ...lifecycleModule,
  ...serviceBookModule,
  ...appraisalModule,
  ...aparModule,
  ...gpfModule,
  ...npsModule,
  ...cpfModule,
  ...deputationModule,
  ...claimsModule,
  ...schedulerModule,
  ...disciplinaryModule,
  ...reservationModule,
  ...medicalModule,
  ...boardIntakeModule,
  ...assessmentModule,
  ...trainingAdminModule,
  ...learningModule,
  ...competencyModule,
  ...contractsModule,
  ...manpowerModule,
  ...consultantInvoiceModule,
  ...contractorBillModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * node-postgres-style adapter over the postgres-js client.
 *
 * Several modules (social, device-trust, id-cards, visiting-cards, ai-ml) issue
 * raw parameterised SQL using the classic `pg` `query(text, params)` shape that
 * returns `{ rows, rowCount }`. postgres-js instead exposes a tagged-template
 * client (`sql\`...\``) plus `sql.unsafe(text, params)` which resolves to a
 * row-list array. This thin wrapper bridges the two so the existing raw-SQL
 * handlers keep their behaviour while remaining type-safe. Preserved verbatim
 * across the TenantRouter-adoption codemod — it wraps the pool-tier
 * `sqlClient` above, unchanged in shape/identity.
 */
export const sqlPool = {
  async query<T = any>(
    text: string,
    params: readonly unknown[] = [],
  ): Promise<{ rows: T[]; rowCount: number }> {
    const result = await sqlClient.unsafe(text, params as unknown as never[]);
    const rows = result as unknown as T[];
    const rowCount = (result as unknown as { count?: number }).count ?? rows.length;
    return { rows, rowCount };
  },
};

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain db.select() runs on a pooled connection with no
 * app.tenant_id GUC set, so under a NOBYPASSRLS role (hrms_svc / identity_svc)
 * the fail-closed policy returns ZERO rows. Wrapping the read in db.transaction
 * makes wrapWithTenantGuc set the GUC from AsyncLocalStorage - reads are then
 * correctly tenant-scoped by RLS, not merely by an app-layer WHERE. Mirrors
 * court-service / visitor-service / meeting-service.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<Db["transaction"]>[0]) as Promise<T>;
}
