/**
 * telephony-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as callsModule } from "../modules/calls/schema.js";
import { schema as queuesModule } from "../modules/queues/schema.js";
import { schema as agentsModule } from "../modules/agents/schema.js";
import { schema as didModule } from "../modules/did/schema.js";
import { schema as ivrModule } from "../modules/ivr/schema.js";
import { schema as recordingsModule } from "../modules/recordings/schema.js";
import { schema as transcriptionModule } from "../modules/transcription/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...callsModule,
  ...queuesModule,
  ...agentsModule,
  ...didModule,
  ...ivrModule,
  ...recordingsModule,
  ...transcriptionModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
