/**
 * procurement-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as indentModule }   from "../modules/indent/schema.js";
import { schema as vendorModule }   from "../modules/vendor/schema.js";
import { schema as poModule }       from "../modules/po/schema.js";
import { schema as grnModule }      from "../modules/grn/schema.js";
import { schema as rfqModule }      from "../modules/rfq/schema.js";
import { schema as tenderModule }   from "../modules/tender/schema.js";
import { schema as auctionModule }  from "../modules/auction/schema.js";
import { schema as paymentsModule } from "../modules/payments/schema.js";
import { schema as blacklistModule } from "../modules/vendor-blacklist/schema.js";
import { schema as threeWayModule }  from "../modules/three-way-match/schema.js";
import { schema as securityModule }  from "../modules/security/schema.js";
import { schema as resolutionIntakeModule } from "../modules/resolution-intake/schema.js";
import { schema as planningModule } from "../modules/planning/schema.js";
import { scorecardSchema as vendorPerfModule } from "../modules/vendor/scorecard-schema.js";
import { outboxSchema }             from "./outbox.js";
import { docCountersSchema }         from "./numbering.js";

const SCHEMA = {
  ...indentModule,
  ...vendorModule,
  ...poModule,
  ...grnModule,
  ...rfqModule,
  ...tenderModule,
  ...auctionModule,
  ...paymentsModule,
  ...blacklistModule,
  ...threeWayModule,
  ...securityModule,
  ...resolutionIntakeModule,
  ...planningModule,
  ...vendorPerfModule,
  ...docCountersSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
