-- Municipal Sec5 service databases + login roles (17 services).
-- AUTO-GENERATED by scripts/dev/generate-municipal-bootstrap.mjs — re-run to refresh.
-- Idempotent: safe to re-run. Run as Postgres superuser / civitas against postgres db.
-- Migrations (0001_init.sql) create module schemas; this file only provisions L1.

-- ── shop (shop-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'shop_svc') THEN
    CREATE ROLE shop_svc WITH LOGIN PASSWORD 'shop_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_shop OWNER shop_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_shop') \gexec
REVOKE ALL ON DATABASE civitas_shop FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_shop TO shop_svc;

-- ── trade (trade-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'trade_svc') THEN
    CREATE ROLE trade_svc WITH LOGIN PASSWORD 'trade_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_trade OWNER trade_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_trade') \gexec
REVOKE ALL ON DATABASE civitas_trade FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_trade TO trade_svc;

-- ── building (building-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'building_svc') THEN
    CREATE ROLE building_svc WITH LOGIN PASSWORD 'building_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_building OWNER building_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_building') \gexec
REVOKE ALL ON DATABASE civitas_building FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_building TO building_svc;

-- ── fire (fire-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fire_svc') THEN
    CREATE ROLE fire_svc WITH LOGIN PASSWORD 'fire_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_fire OWNER fire_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_fire') \gexec
REVOKE ALL ON DATABASE civitas_fire FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_fire TO fire_svc;

-- ── advertisement (advertisement-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'advertisement_svc') THEN
    CREATE ROLE advertisement_svc WITH LOGIN PASSWORD 'advertisement_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_advertisement OWNER advertisement_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_advertisement') \gexec
REVOKE ALL ON DATABASE civitas_advertisement FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_advertisement TO advertisement_svc;

-- ── vendor (vendor-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'vendor_svc') THEN
    CREATE ROLE vendor_svc WITH LOGIN PASSWORD 'vendor_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_vendor OWNER vendor_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_vendor') \gexec
REVOKE ALL ON DATABASE civitas_vendor FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_vendor TO vendor_svc;

-- ── roadcut (roadcut-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'roadcut_svc') THEN
    CREATE ROLE roadcut_svc WITH LOGIN PASSWORD 'roadcut_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_roadcut OWNER roadcut_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_roadcut') \gexec
REVOKE ALL ON DATABASE civitas_roadcut FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_roadcut TO roadcut_svc;

-- ── event (event-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'event_svc') THEN
    CREATE ROLE event_svc WITH LOGIN PASSWORD 'event_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_event OWNER event_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_event') \gexec
REVOKE ALL ON DATABASE civitas_event FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_event TO event_svc;

-- ── refund (refund-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'refund_svc') THEN
    CREATE ROLE refund_svc WITH LOGIN PASSWORD 'refund_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_refund OWNER refund_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_refund') \gexec
REVOKE ALL ON DATABASE civitas_refund FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_refund TO refund_svc;

-- ── sewerage (sewerage-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sewerage_svc') THEN
    CREATE ROLE sewerage_svc WITH LOGIN PASSWORD 'sewerage_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_sewerage OWNER sewerage_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_sewerage') \gexec
REVOKE ALL ON DATABASE civitas_sewerage FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_sewerage TO sewerage_svc;

-- ── swm (swm-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'swm_svc') THEN
    CREATE ROLE swm_svc WITH LOGIN PASSWORD 'swm_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_swm OWNER swm_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_swm') \gexec
REVOKE ALL ON DATABASE civitas_swm FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_swm TO swm_svc;

-- ── drainage (drainage-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'drainage_svc') THEN
    CREATE ROLE drainage_svc WITH LOGIN PASSWORD 'drainage_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_drainage OWNER drainage_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_drainage') \gexec
REVOKE ALL ON DATABASE civitas_drainage FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_drainage TO drainage_svc;

-- ── parks (parks-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'parks_svc') THEN
    CREATE ROLE parks_svc WITH LOGIN PASSWORD 'parks_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_parks OWNER parks_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_parks') \gexec
REVOKE ALL ON DATABASE civitas_parks FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_parks TO parks_svc;

-- ── animal (animal-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'animal_svc') THEN
    CREATE ROLE animal_svc WITH LOGIN PASSWORD 'animal_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_animal OWNER animal_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_animal') \gexec
REVOKE ALL ON DATABASE civitas_animal FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_animal TO animal_svc;

-- ── crematorium (crematorium-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'crematorium_svc') THEN
    CREATE ROLE crematorium_svc WITH LOGIN PASSWORD 'crematorium_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_crematorium OWNER crematorium_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_crematorium') \gexec
REVOKE ALL ON DATABASE civitas_crematorium FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_crematorium TO crematorium_svc;

-- ── parking (parking-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'parking_svc') THEN
    CREATE ROLE parking_svc WITH LOGIN PASSWORD 'parking_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_parking OWNER parking_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_parking') \gexec
REVOKE ALL ON DATABASE civitas_parking FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_parking TO parking_svc;

-- ── market (market-service) ──
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'market_svc') THEN
    CREATE ROLE market_svc WITH LOGIN PASSWORD 'market_dev_pw' NOSUPERUSER NOCREATEDB NOBYPASSRLS;
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_market OWNER market_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_market') \gexec
REVOKE ALL ON DATABASE civitas_market FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_market TO market_svc;

