-- AUTO-GENERATED by gen_bootstrap.mjs — do not edit by hand.
-- Run the cluster-level section as a superuser; the per-DB sections \connect into each DB.

-- ================= tenant service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'tenant_svc') THEN
    CREATE ROLE tenant_svc LOGIN PASSWORD 'tenant_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_tenant OWNER tenant_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_tenant')\gexec
REVOKE ALL ON DATABASE civitas_tenant FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_tenant TO tenant_svc;

\connect civitas_tenant
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS tenant AUTHORIZATION tenant_svc;
CREATE SCHEMA IF NOT EXISTS orgunit AUTHORIZATION tenant_svc;
CREATE SCHEMA IF NOT EXISTS settings AUTHORIZATION tenant_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION tenant_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION tenant_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE tenant_svc_tenant LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA tenant TO tenant_svc_tenant;
-- CREATE ROLE tenant_svc_orgunit LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA orgunit TO tenant_svc_orgunit;
-- CREATE ROLE tenant_svc_settings LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA settings TO tenant_svc_settings;


-- ================= identity service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'identity_svc') THEN
    CREATE ROLE identity_svc LOGIN PASSWORD 'identity_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_identity OWNER identity_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_identity')\gexec
REVOKE ALL ON DATABASE civitas_identity FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_identity TO identity_svc;

\connect civitas_identity
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS users AUTHORIZATION identity_svc;
CREATE SCHEMA IF NOT EXISTS sessions AUTHORIZATION identity_svc;
CREATE SCHEMA IF NOT EXISTS mfa AUTHORIZATION identity_svc;
CREATE SCHEMA IF NOT EXISTS service_accounts AUTHORIZATION identity_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION identity_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION identity_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE identity_svc_users LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA users TO identity_svc_users;
-- CREATE ROLE identity_svc_sessions LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA sessions TO identity_svc_sessions;
-- CREATE ROLE identity_svc_mfa LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA mfa TO identity_svc_mfa;
-- CREATE ROLE identity_svc_service_accounts LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA service_accounts TO identity_svc_service_accounts;


-- ================= policy service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'policy_svc') THEN
    CREATE ROLE policy_svc LOGIN PASSWORD 'policy_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_policy OWNER policy_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_policy')\gexec
REVOKE ALL ON DATABASE civitas_policy FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_policy TO policy_svc;

\connect civitas_policy
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS roles AUTHORIZATION policy_svc;
CREATE SCHEMA IF NOT EXISTS bindings AUTHORIZATION policy_svc;
CREATE SCHEMA IF NOT EXISTS abac AUTHORIZATION policy_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION policy_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION policy_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE policy_svc_roles LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA roles TO policy_svc_roles;
-- CREATE ROLE policy_svc_bindings LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA bindings TO policy_svc_bindings;
-- CREATE ROLE policy_svc_abac LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA abac TO policy_svc_abac;


-- ================= audit service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'audit_svc') THEN
    CREATE ROLE audit_svc LOGIN PASSWORD 'audit_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_audit OWNER audit_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_audit')\gexec
REVOKE ALL ON DATABASE civitas_audit FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_audit TO audit_svc;

\connect civitas_audit
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS events AUTHORIZATION audit_svc;
CREATE SCHEMA IF NOT EXISTS exports AUTHORIZATION audit_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION audit_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION audit_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE audit_svc_events LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA events TO audit_svc_events;
-- CREATE ROLE audit_svc_exports LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA exports TO audit_svc_exports;


-- ================= finance service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'finance_svc') THEN
    CREATE ROLE finance_svc LOGIN PASSWORD 'finance_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_finance OWNER finance_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_finance')\gexec
REVOKE ALL ON DATABASE civitas_finance FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_finance TO finance_svc;

\connect civitas_finance
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS budget AUTHORIZATION finance_svc;
CREATE SCHEMA IF NOT EXISTS gl AUTHORIZATION finance_svc;
CREATE SCHEMA IF NOT EXISTS treasury AUTHORIZATION finance_svc;
CREATE SCHEMA IF NOT EXISTS payments AUTHORIZATION finance_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION finance_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION finance_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE finance_svc_budget LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA budget TO finance_svc_budget;
-- CREATE ROLE finance_svc_gl LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA gl TO finance_svc_gl;
-- CREATE ROLE finance_svc_treasury LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA treasury TO finance_svc_treasury;
-- CREATE ROLE finance_svc_payments LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA payments TO finance_svc_payments;


-- ================= procurement service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'procurement_svc') THEN
    CREATE ROLE procurement_svc LOGIN PASSWORD 'procurement_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_procurement OWNER procurement_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_procurement')\gexec
REVOKE ALL ON DATABASE civitas_procurement FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_procurement TO procurement_svc;

\connect civitas_procurement
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS pr AUTHORIZATION procurement_svc;
CREATE SCHEMA IF NOT EXISTS rfq AUTHORIZATION procurement_svc;
CREATE SCHEMA IF NOT EXISTS po AUTHORIZATION procurement_svc;
CREATE SCHEMA IF NOT EXISTS grn AUTHORIZATION procurement_svc;
CREATE SCHEMA IF NOT EXISTS contract AUTHORIZATION procurement_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION procurement_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION procurement_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE procurement_svc_pr LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA pr TO procurement_svc_pr;
-- CREATE ROLE procurement_svc_rfq LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA rfq TO procurement_svc_rfq;
-- CREATE ROLE procurement_svc_po LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA po TO procurement_svc_po;
-- CREATE ROLE procurement_svc_grn LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA grn TO procurement_svc_grn;
-- CREATE ROLE procurement_svc_contract LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA contract TO procurement_svc_contract;


-- ================= notification service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'notification_svc') THEN
    CREATE ROLE notification_svc LOGIN PASSWORD 'notification_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_notification OWNER notification_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_notification')\gexec
REVOKE ALL ON DATABASE civitas_notification FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_notification TO notification_svc;

\connect civitas_notification
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS templates AUTHORIZATION notification_svc;
CREATE SCHEMA IF NOT EXISTS deliveries AUTHORIZATION notification_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION notification_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION notification_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE notification_svc_templates LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA templates TO notification_svc_templates;
-- CREATE ROLE notification_svc_deliveries LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA deliveries TO notification_svc_deliveries;


-- ================= billing service =================
-- L1: dedicated login + database, no access to anything else.
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'billing_svc') THEN
    CREATE ROLE billing_svc LOGIN PASSWORD 'billing_dev_pw';
  END IF;
END $$;
SELECT 'CREATE DATABASE civitas_billing OWNER billing_svc'
  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'civitas_billing')\gexec
REVOKE ALL ON DATABASE civitas_billing FROM PUBLIC;
GRANT CONNECT ON DATABASE civitas_billing TO billing_svc;

\connect civitas_billing
REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use
-- L2: one schema per bounded-context module, owned by the service role.
CREATE SCHEMA IF NOT EXISTS subscriptions AUTHORIZATION billing_svc;
CREATE SCHEMA IF NOT EXISTS invoices AUTHORIZATION billing_svc;
CREATE SCHEMA IF NOT EXISTS metering AUTHORIZATION billing_svc;
CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION billing_svc;  -- transactional outbox
CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION billing_svc;  -- consumer idempotency / processed-message log

-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,
-- and connect each module's repo pool with that role. Commented by default.
-- CREATE ROLE billing_svc_subscriptions LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA subscriptions TO billing_svc_subscriptions;
-- CREATE ROLE billing_svc_invoices LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA invoices TO billing_svc_invoices;
-- CREATE ROLE billing_svc_metering LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA metering TO billing_svc_metering;

