#!/usr/bin/env node
/**
 * Generate the DB-per-service bootstrap SQL from services.json.
 *
 *   node gen_bootstrap.mjs > bootstrap.generated.sql
 *
 * Enforces the inviolable rules (ARCHITECTURE.md):
 *   L1 — one database + one login per service; the login is granted CONNECT only on
 *        its own database. No cross-database grants exist, so a service physically
 *        cannot reach another service's data (Postgres can't cross databases anyway).
 *   L2 — one schema per bounded-context module inside the service DB; PUBLIC is
 *        revoked so only the service role can use them.
 *
 * Passwords come from env vars named {ROLE_UPPER}_PASSWORD (sourced from Vault),
 * never committed. Run cluster-level statements as a superuser/admin.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const cfg = JSON.parse(readFileSync(join(here, "services.json"), "utf8"));

const out = [];
out.push("-- AUTO-GENERATED by gen_bootstrap.mjs — do not edit by hand.");
out.push("-- Run the cluster-level section as a superuser; the per-DB sections \\connect into each DB.\n");

for (const s of cfg.services) {
  const pwEnv = `${s.role.toUpperCase()}_PASSWORD`;
  const pw = process.env[pwEnv];
  if (!pw) {
    out.push(`-- WARNING: ${pwEnv} not set; emitting placeholder. Set it from Vault before applying.`);
  }
  const pwLiteral = (pw ?? `__SET_${pwEnv}__`).replace(/'/g, "''");

  out.push(`-- ================= ${s.service} service =================`);
  out.push(`-- L1: dedicated login + database, no access to anything else.`);
  out.push(`DO $$ BEGIN`);
  out.push(`  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${s.role}') THEN`);
  out.push(`    CREATE ROLE ${s.role} LOGIN PASSWORD '${pwLiteral}';`);
  out.push(`  END IF;`);
  out.push(`END $$;`);
  out.push(`SELECT 'CREATE DATABASE ${s.db} OWNER ${s.role}'`);
  out.push(`  WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${s.db}')\\gexec`);
  out.push(`REVOKE ALL ON DATABASE ${s.db} FROM PUBLIC;`);
  out.push(`GRANT CONNECT ON DATABASE ${s.db} TO ${s.role};`);
  out.push("");
  out.push(`\\connect ${s.db}`);
  out.push(`REVOKE ALL ON SCHEMA public FROM PUBLIC;            -- no default public schema use`);
  out.push(`-- L2: one schema per bounded-context module, owned by the service role.`);
  for (const m of s.modules) {
    out.push(`CREATE SCHEMA IF NOT EXISTS ${m} AUTHORIZATION ${s.role};`);
  }
  out.push(`CREATE SCHEMA IF NOT EXISTS _outbox AUTHORIZATION ${s.role};  -- transactional outbox`);
  out.push(`CREATE SCHEMA IF NOT EXISTS _inbox  AUTHORIZATION ${s.role};  -- consumer idempotency / processed-message log`);
  out.push("");
  out.push(`-- OPTIONAL hard L2: give each module its own role with USAGE on its own schema only,`);
  out.push(`-- and connect each module's repo pool with that role. Commented by default.`);
  for (const m of s.modules) {
    out.push(`-- CREATE ROLE ${s.role}_${m} LOGIN PASSWORD '__VAULT__'; GRANT USAGE ON SCHEMA ${m} TO ${s.role}_${m};`);
  }
  out.push("\n");
}

process.stdout.write(out.join("\n"));
