/**
 * location-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as locationsModule } from "../modules/locations/schema.js";
import { schema as hierarchyModule } from "../modules/hierarchy/schema.js";
import { schema as jurisdictionModule } from "../modules/jurisdiction/schema.js";
import { schema as geofenceModule } from "../modules/geofence/schema.js";
import { schema as pincodeModule } from "../modules/pincode/schema.js";
import { schema as landRecordsModule } from "../modules/land-records/schema.js";
import { schema as cadastralModule } from "../modules/cadastral/schema.js";
import { schema as infrastructureModule } from "../modules/infrastructure/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...locationsModule,
  ...hierarchyModule,
  ...jurisdictionModule,
  ...geofenceModule,
  ...pincodeModule,
  ...landRecordsModule,
  ...cadastralModule,
  ...infrastructureModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes createTenantDb's
 * `wrapWithTenantGuc`-wrapped `db` set the GUC from AsyncLocalStorage -- reads
 * are then correctly tenant-scoped by RLS, not merely by an app-layer WHERE.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => PromiseLike<T>): Promise<T> {
  return db.transaction(fn as (tx: ScopedTx) => Promise<T>);
}
