/**
 * location-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as locationsModule } from "../modules/locations/schema.js";
import { schema as hierarchyModule } from "../modules/hierarchy/schema.js";
import { schema as jurisdictionModule } from "../modules/jurisdiction/schema.js";
import { schema as geofenceModule } from "../modules/geofence/schema.js";
import { schema as pincodeModule } from "../modules/pincode/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...locationsModule,
  ...hierarchyModule,
  ...jurisdictionModule,
  ...geofenceModule,
  ...pincodeModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
