/**
 * policy-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { rolesModuleSchema } from "../modules/roles/schema.js";
import { bindingsModuleSchema } from "../modules/bindings/schema.js";
import { abacModuleSchema } from "../modules/abac/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...rolesModuleSchema,
  ...bindingsModuleSchema,
  ...abacModuleSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
