/**
 * stock-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as itemModule }       from "../modules/item/schema.js";
import { schema as warehouseModule }  from "../modules/warehouse/schema.js";
import { schema as ledgerModule }     from "../modules/ledger/schema.js";
import { schema as entryModule }      from "../modules/entry/schema.js";
import { schema as valuationModule }  from "../modules/valuation/schema.js";
import { schema as receiptModule }    from "../modules/receipt/schema.js";
import { schema as ewayBillModule }   from "../modules/eway-bill/schema.js";
import { outboxSchema }               from "./outbox.js";

const SCHEMA = {
  ...itemModule,
  ...warehouseModule,
  ...ledgerModule,
  ...entryModule,
  ...valuationModule,
  ...receiptModule,
  ...ewayBillModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Drizzle transaction handle exposed to {@link scopedRead} callbacks.
 * Preserves full column typing (the public db.transaction rewrites tx to any).
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];

/**
 * Executes a read-only callback inside a Postgres transaction so that the
 * tenant-aware GUC (`app.tenant_id`) is set from AsyncLocalStorage. Without
 * this wrapper, bare `db.select()` calls bypass RLS because the GUC is only
 * injected by `wrapWithTenantGuc` inside `db.transaction()`.
 */
export function scopedRead<T>(fn: (tx: ScopedTx) => Promise<T>): Promise<T> {
  return db.transaction(fn as Parameters<Db["transaction"]>[0]) as Promise<T>;
}
