/**
 * stock-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as itemModule }       from "../modules/item/schema.js";
import { schema as warehouseModule }  from "../modules/warehouse/schema.js";
import { schema as ledgerModule }     from "../modules/ledger/schema.js";
import { schema as entryModule }      from "../modules/entry/schema.js";
import { schema as valuationModule }  from "../modules/valuation/schema.js";
import { schema as receiptModule }    from "../modules/receipt/schema.js";
import { schema as ewayBillModule }   from "../modules/eway-bill/schema.js";
import { outboxSchema }               from "./outbox.js";

const SCHEMA = {
  ...itemModule,
  ...warehouseModule,
  ...ledgerModule,
  ...entryModule,
  ...valuationModule,
  ...receiptModule,
  ...ewayBillModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
