/**
 * project-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as projectModule }     from "../modules/project/schema.js";
import { schema as schemeModule }      from "../modules/scheme/schema.js";
import { schema as progressModule }    from "../modules/progress/schema.js";
import { schema as utilisationModule } from "../modules/utilisation/schema.js";
import { schema as geoModule }         from "../modules/geo/schema.js";
import { schema as schedulingModule }  from "../modules/scheduling/schema.js";
import { baselinesSchema }             from "../modules/scheduling/baselines.js";
import { schema as boardIntakeModule } from "../modules/board-intake/schema.js";
import { outboxSchema }                from "./outbox.js";

const SCHEMA = {
  ...projectModule,
  ...schemeModule,
  ...progressModule,
  ...utilisationModule,
  ...geoModule,
  ...schedulingModule,
  ...baselinesSchema,
  ...boardIntakeModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
