/**
 * citizen-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as portalModule }      from "../modules/portal/schema.js";
import { schema as applicationModule } from "../modules/application/schema.js";
import { schema as grievanceModule }   from "../modules/grievance/schema.js";
import { schema as rtiModule }         from "../modules/rti/schema.js";
import { schema as helpdeskModule }    from "../modules/helpdesk/schema.js";
import { schema as analyticsModule }   from "../modules/analytics/schema.js";
import { schema as slaRulesModule }    from "../modules/sla-rules/schema.js";
import { outboxSchema }                from "./outbox.js";

const SCHEMA = {
  ...portalModule,
  ...applicationModule,
  ...grievanceModule,
  ...rtiModule,
  ...helpdeskModule,
  ...analyticsModule,
  ...slaRulesModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
