/**
 * PAY-PROFILES byte-identity proof, run level (real DB, real consumer).
 *
 * A fixed 11-employee govt-scale tenant (NPS / GPF / EPF, X / Y / Z, LOP, a
 * mid-month joiner, an old-regime employee, an ESI-eligible low earner, a
 * back-dated salary revision that generates retro arrears, a structure
 * earning + deduction, and a consultant the run must skip) is paid for
 * 2026-08 through POST /v1/payroll/runs. Every pre-existing money column the
 * run writes -- slips (incl. the components jsonb), statutory PF / GPF / NPS
 * / ESI / TDS rows, retro-arrear rows, the department register and the run
 * totals -- is dumped and compared with tests/fixtures/
 * pay-profiles-legacy-run-snapshot.json.
 *
 * That snapshot was GENERATED BY THIS SAME FILE RUNNING ON origin/main
 * (before PAY-PROFILES), with PAY_PROFILES_WRITE_SNAPSHOT=1. The file only
 * uses APIs that exist on main, so it can regenerate the snapshot there. The
 * HRMS feed carries no pay profiles (an employee with no approved profile ==
 * govt_scale) and 2026-08 is before any HRA-floor go-live, so PAY-PROFILES
 * must reproduce the legacy run exactly.
 */
import { describe, it, expect, vi, beforeAll, afterAll } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { sql } from "drizzle-orm";
import { runWithTenant } from "@civitasone/db";
import { signToken } from "@civitasone/auth";

vi.mock("../src/shared/hrms-client.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../src/shared/hrms-client.js")>();
  return { ...actual, fetchPayrollInput: vi.fn(), fetchEmployeeSummaries: vi.fn() };
});
import { fetchPayrollInput, fetchEmployeeSummaries } from "../src/shared/hrms-client.js";
import { buildApp } from "../src/app.js";
import { db, sqlClient } from "../src/shared/db.js";
import { queue } from "../src/shared/infra.js";
import { registerPayrollConsumers } from "../src/modules/payroll/consumer.js";
import type { FastifyInstance } from "fastify";

const SNAPSHOT = join(__dirname, "fixtures", "pay-profiles-legacy-run-snapshot.json");
const SECRET = process.env.JWT_SECRET ?? "test_secret_for_civitasone_32chr";
const TENANT = "7a7a7a7a-0000-4000-8000-00000000a001";
const ACTOR = "7a7a7a7a-0000-4000-8000-00000000a0a0";
const STRUCTURE = "7a7a7a7a-0000-4000-8000-00000000a0b0";
const DEPT_A = "7a7a7a7a-0000-4000-8000-00000000d001";
const DEPT_B = "7a7a7a7a-0000-4000-8000-00000000d002";
const MONTH = "2026-08";
const empId = (n: number) => `7a7a7a7a-0000-4000-8000-0000000000${String(n).padStart(2, "0")}`;

type Emp = { n: number; basic: number; city: "X" | "Y" | "Z"; scheme: "NPS" | "GPF" | "EPF"; doj?: string; regime?: "old" | "new"; dept?: string; route?: string };
const EMPLOYEES: Emp[] = [
  { n: 1, basic: 5_610_000, city: "X", scheme: "NPS" },
  { n: 2, basic: 1_500_000, city: "X", scheme: "EPF" },
  { n: 3, basic: 4_490_000, city: "Y", scheme: "GPF" },               // back-dated revision below
  { n: 4, basic: 1_800_000, city: "Z", scheme: "EPF", dept: DEPT_B },
  { n: 5, basic: 800_000, city: "Y", scheme: "EPF" },                  // ESI-eligible
  { n: 6, basic: 6_770_000, city: "Z", scheme: "NPS", doj: "2026-08-10" }, // mid-month joiner
  { n: 7, basic: 3_500_000, city: "X", scheme: "NPS" },                // 3 LOP days
  { n: 8, basic: 2_500_000, city: "Y", scheme: "EPF", regime: "old", dept: DEPT_B },
  { n: 9, basic: 9_000_000, city: "X", scheme: "NPS", route: "invoice" }, // consultant: skipped
  { n: 10, basic: 12_000_000, city: "X", scheme: "NPS" },             // TDS
  { n: 11, basic: 4_000_000, city: "Z", scheme: "GPF", dept: DEPT_B },  // 1 LOP day
];

function feed() {
  return {
    month: MONTH,
    employees: EMPLOYEES.map((e) => ({
      id: empId(e.n), employeeNo: `SNAP-${String(e.n).padStart(2, "0")}`, fullName: `Snapshot ${e.n}`,
      basicMinor: String(e.basic), dateOfJoining: e.doj ?? "2018-04-01", payStructureId: null,
      bankAccountNo: null, bankIfsc: null, pan: null, uan: null, pran: null,
      cityClass: e.city, taxRegime: e.regime ?? "new", departmentId: e.dept ?? DEPT_A, pensionScheme: e.scheme,
      paymentRoute: e.route ?? "payroll", eligibleForPayroll: (e.route ?? "payroll") === "payroll",
      statutoryPf: true, statutoryEsi: true, statutoryNps: e.scheme === "NPS",
    })),
    lopDays: { [empId(7)]: 3, [empId(11)]: 1 },
    overtimeHours: {},
  };
}

const asTenant = <T>(fn: (tx: Parameters<Parameters<typeof db.transaction>[0]>[0]) => Promise<T>) =>
  runWithTenant(TENANT, () => db.transaction(fn));

async function cleanup(): Promise<void> {
  await asTenant(async (tx) => {
    for (const t of ["statutory.payroll_pf", "statutory.payroll_esi", "statutory.payroll_tds", "statutory.payroll_gpf", "statutory.payroll_nps"]) {
      await tx.execute(sql.raw(`DELETE FROM ${t} WHERE tenant_id = '${TENANT}'`));
    }
    for (const t of ["payroll.payroll_register", "payroll.payroll_slips", "payroll.payroll_arrears", "payroll.payroll_runs",
      "payroll.payroll_components", "payroll.payroll_structures", "payroll.payroll_salary_revisions", "payroll.dearness_allowance_rates"]) {
      await tx.execute(sql.raw(`DELETE FROM ${t} WHERE tenant_id = '${TENANT}'`));
    }
  });
}

async function seed(): Promise<void> {
  await asTenant(async (tx) => {
    await tx.execute(sql`INSERT INTO payroll.dearness_allowance_rates (tenant_id, effective_from, rate_bps) VALUES (${TENANT}::uuid, '2024-01-01', 5000)`);
    await tx.execute(sql`INSERT INTO payroll.dearness_allowance_rates (tenant_id, effective_from, rate_bps) VALUES (${TENANT}::uuid, '2026-07-01', 5500)`);
    await tx.execute(sql`
      INSERT INTO payroll.payroll_structures (id, tenant_id, name, is_default, status, created_by, updated_by)
      VALUES (${STRUCTURE}::uuid, ${TENANT}::uuid, 'Snapshot Structure', true, 'active', ${ACTOR}::uuid, ${ACTOR}::uuid)`);
    await tx.execute(sql`
      INSERT INTO payroll.payroll_components (tenant_id, structure_id, code, name, component_type, fixed_minor, created_by, updated_by)
      VALUES (${TENANT}::uuid, ${STRUCTURE}::uuid, 'TA', 'Transport Allowance', 'earning', 360000, ${ACTOR}::uuid, ${ACTOR}::uuid),
             (${TENANT}::uuid, ${STRUCTURE}::uuid, 'WELFARE', 'Welfare Fund', 'deduction', 10000, ${ACTOR}::uuid, ${ACTOR}::uuid)`);
    await tx.execute(sql`
      INSERT INTO payroll.payroll_components (tenant_id, structure_id, code, name, component_type, pct_of_basic, created_by, updated_by)
      VALUES (${TENANT}::uuid, ${STRUCTURE}::uuid, 'SPL', 'Special Pay', 'earning', 2.5, ${ACTOR}::uuid, ${ACTOR}::uuid)`);
    await tx.execute(sql`
      INSERT INTO payroll.payroll_salary_revisions (tenant_id, employee_id, effective_date, old_basic_minor, new_basic_minor, old_gross_minor, new_gross_minor, revision_type)
      VALUES (${TENANT}::uuid, ${empId(3)}::uuid, '2026-06-01', 4360000, 4490000, 0, 0, 'annual_increment')`);
  });
}

async function waitForRun(runId: string): Promise<void> {
  const deadline = Date.now() + 30_000;
  for (;;) {
    await new Promise((r) => setTimeout(r, 250));
    const rows = (await asTenant((tx) => tx.execute(sql`SELECT status, last_error FROM payroll.payroll_runs WHERE id = ${runId}::uuid`))) as unknown as Array<{ status: string; last_error: string | null }>;
    if (rows[0]?.status === "failed") throw new Error(`run failed: ${rows[0].last_error}`);
    const n = (await asTenant((tx) => tx.execute(sql`SELECT count(*)::int AS n FROM payroll.payroll_register WHERE run_id = ${runId}::uuid`))) as unknown as Array<{ n: number }>;
    if ((n[0]?.n ?? 0) > 0) return;
    if (Date.now() > deadline) throw new Error("run did not complete");
  }
}

/** Every legacy column the run writes, ids/timestamps stripped, deterministically ordered. */
async function dump(runId: string): Promise<Record<string, unknown>> {
  const q = async (s: ReturnType<typeof sql>) => (await asTenant((tx) => tx.execute(s))) as unknown as Array<Record<string, unknown>>;
  const str = (rows: Array<Record<string, unknown>>) => JSON.parse(JSON.stringify(rows, (_k, v) => (typeof v === "bigint" ? v.toString() : v)));
  return str([
    { run: await q(sql`SELECT month, run_type, status, total_gross_minor::text, total_net_minor::text FROM payroll.payroll_runs WHERE id = ${runId}::uuid`) },
    { slips: await q(sql`
      SELECT employee_id, employee_no, basic_minor::text, gross_minor::text, total_deductions_minor::text, net_pay_minor::text,
             components, pf_employee_minor::text, pf_employer_minor::text, gpf_minor::text, nps_employee_minor::text,
             nps_employer_minor::text, esi_minor::text, tds_minor::text, status, currency
      FROM payroll.payroll_slips WHERE run_id = ${runId}::uuid ORDER BY employee_no`) },
    { pf: await q(sql`SELECT employee_id, basic_minor::text, emp_contrib_pct::text, er_contrib_pct::text, emp_contrib_minor::text, er_contrib_minor::text, eps_contrib_minor::text, epf_er_contrib_minor::text, period FROM statutory.payroll_pf WHERE run_id = ${runId}::uuid ORDER BY employee_id`) },
    { gpf: await q(sql`SELECT employee_id, basic_minor::text, contrib_pct::text, emp_contrib_minor::text, period FROM statutory.payroll_gpf WHERE run_id = ${runId}::uuid ORDER BY employee_id`) },
    { nps: await q(sql`SELECT employee_id, basic_minor::text, emp_contrib_minor::text, er_contrib_minor::text, period FROM statutory.payroll_nps WHERE run_id = ${runId}::uuid ORDER BY employee_id`) },
    { esi: await q(sql`SELECT employee_id, gross_minor::text, emp_contrib_minor::text, er_contrib_minor::text, period FROM statutory.payroll_esi WHERE run_id = ${runId}::uuid ORDER BY employee_id`) },
    { tds: await q(sql`SELECT employee_id, annual_basic_minor::text, taxable_minor::text, tds_minor::text, period FROM statutory.payroll_tds WHERE run_id = ${runId}::uuid ORDER BY employee_id`) },
    { arrears: await q(sql`SELECT employee_id, component_code, from_period, to_period, old_amount_minor::text, new_amount_minor::text, difference_minor::text, status, source FROM payroll.payroll_arrears WHERE tenant_id = ${TENANT}::uuid ORDER BY employee_id, from_period, component_code`) },
    { register: await q(sql`SELECT department_id, employee_count, total_gross_minor::text, total_deductions_minor::text, total_net_minor::text, total_pf_minor::text, total_esi_minor::text, total_tds_minor::text, total_pt_minor::text, period FROM payroll.payroll_register WHERE run_id = ${runId}::uuid ORDER BY department_id`) },
  ]);
}

let app: FastifyInstance;

beforeAll(async () => {
  const rawSubscribe = queue.subscribe.bind(queue);
  (queue as unknown as { subscribe: typeof queue.subscribe }).subscribe = ((topic: string, handler: (msg: { tenantId: string }) => Promise<void>) =>
    rawSubscribe(topic, (msg: { tenantId: string }) => runWithTenant(msg.tenantId, () => handler(msg)))) as unknown as typeof queue.subscribe;
  registerPayrollConsumers(queue);
  await queue.start();
  app = await buildApp();
  vi.mocked(fetchPayrollInput).mockImplementation(async () => feed() as unknown as Awaited<ReturnType<typeof fetchPayrollInput>>);
  vi.mocked(fetchEmployeeSummaries).mockImplementation(async () => new Map(EMPLOYEES.map((e) => [empId(e.n), {
    fullName: `Snapshot ${e.n}`, departmentName: e.dept === DEPT_B ? "Dept B" : "Dept A", employeeNo: `SNAP-${String(e.n).padStart(2, "0")}`,
  }])));
  await cleanup();
  await seed();
});

afterAll(async () => {
  await cleanup();
  await app.close();
  await sqlClient.end();
});

describe("PAY-PROFILES: a govt-scale run is byte-identical to origin/main", () => {
  it("reproduces every legacy column of the pre-PAY-PROFILES snapshot", async () => {
    const res = await app.inject({
      method: "POST", url: "/v1/payroll/runs",
      headers: { authorization: `Bearer ${signToken({ sub: ACTOR, tid: TENANT, roles: ["payroll_admin"], sid: "snap" }, SECRET, 3600)}`, "content-type": "application/json" },
      payload: { runNo: "SNAP-2026-08", month: MONTH, structureId: STRUCTURE },
    });
    expect([201, 202]).toContain(res.statusCode);
    const runId: string = res.json().data?.id ?? res.json().id;
    await waitForRun(runId);
    const actual = await dump(runId);
    if (process.env.PAY_PROFILES_WRITE_SNAPSHOT === "1") {
      writeFileSync(SNAPSHOT, `${JSON.stringify(actual, null, 2)}\n`);
    }
    const expected = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as unknown;
    expect(actual).toEqual(expected);
  }, 60_000);
});
