/**
 * Real-DB regression guard for GAP-HR-MEDICAL-04: Claim Ref was "MED/" +
 * the first 8 hex chars of the row's randomUUID() id -- not a stored claim
 * number. Two claims could collide (32 bits of a v4 uuid) and the
 * reference was not resolvable server-side.
 *
 * Fixed via migration 0156: a real, DB-guaranteed-unique, sequential
 * claim_no column (GENERATED BY DEFAULT AS IDENTITY). Verifies it
 * self-assigns on insert, is returned by both POST and GET, is exact
 * (never bigint-as-string surprises), and is server-side searchable.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { randomUUID } from "node:crypto";
import { signToken } from "@civitasone/auth";
import { withTenantScope } from "@civitasone/db";
import { buildApp } from "../app.js";
import { db, sqlClient } from "../shared/db.js";
import { hrmsDepartments, hrmsDesignations, hrmsEmployees } from "../modules/employee/schema.js";
import type { FastifyInstance } from "fastify";

const SECRET = process.env.JWT_SECRET ?? "test_secret_for_civitasone_32chr";
const TENANT = randomUUID();
const HR_ACTOR = randomUUID();

function auth(sub: string, roles: string[]): { authorization: string } {
  const jwt = signToken({ sub, tid: TENANT, roles, sid: "sess-medical-claim-no" }, SECRET, 3600);
  return { authorization: `Bearer ${jwt}` };
}

let app: FastifyInstance;
let employeeId: string;

beforeAll(async () => {
  app = await buildApp();
  employeeId = randomUUID();
  const deptId = randomUUID();
  const desigId = randomUUID();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await withTenantScope(db, TENANT, async (tx: any) => {
    await tx.insert(hrmsDepartments).values({
      id: deptId, tenantId: TENANT, code: "MCNT", name: "Claim No Test Dept",
      isActive: true, createdBy: HR_ACTOR, updatedBy: HR_ACTOR,
    });
    await tx.insert(hrmsDesignations).values({
      id: desigId, tenantId: TENANT, code: "MCNT-D", name: "Claim No Test Designation", level: 5,
      createdBy: HR_ACTOR, updatedBy: HR_ACTOR,
    });
    await tx.insert(hrmsEmployees).values({
      id: employeeId, tenantId: TENANT, employeeNo: "MCN-001", fullName: "Claim No Test Employee",
      departmentId: deptId, designationId: desigId, dateOfJoining: "2020-01-01",
      createdBy: HR_ACTOR, updatedBy: HR_ACTOR,
    });
  });
});

afterAll(async () => {
  await app.close();
  await sqlClient.end();
});

async function submitClaim(amountMinor: number): Promise<{ id: string; claimNo: number }> {
  const res = await app.inject({
    method: "POST", url: "/v1/hrms/medical/claims",
    headers: auth(HR_ACTOR, ["hr_officer"]),
    payload: {
      employeeId, claimType: "outdoor", amountMinor,
      hospitalName: "Test Hospital", diagnosis: "test",
    },
  });
  expect(res.statusCode).toBe(201);
  const body = res.json().data as { id: string; claimNo: number };
  expect(typeof body.claimNo).toBe("number");
  return body;
}

describe("GAP-HR-MEDICAL-04: medical claim_no", () => {
  it("two claims created back-to-back get distinct, sequential claim_no values", async () => {
    const first = await submitClaim(1000);
    const second = await submitClaim(2000);
    expect(second.claimNo).toBeGreaterThan(first.claimNo);
  });

  it("the list route returns the same claim_no the create route assigned", async () => {
    const created = await submitClaim(3000);
    const res = await app.inject({
      method: "GET", url: "/v1/hrms/medical/claims",
      headers: auth(HR_ACTOR, ["hr_officer"]),
    });
    expect(res.statusCode).toBe(200);
    const rows = res.json().data as Array<{ id: string; claim_no: number }>;
    const row = rows.find((r) => r.id === created.id);
    expect(row?.claim_no).toBe(created.claimNo);
  });

  it("claimNo is server-side searchable and returns exactly one row", async () => {
    const created = await submitClaim(4000);
    const res = await app.inject({
      method: "GET", url: `/v1/hrms/medical/claims?claimNo=${created.claimNo}`,
      headers: auth(HR_ACTOR, ["hr_officer"]),
    });
    expect(res.statusCode).toBe(200);
    const rows = res.json().data as Array<{ id: string }>;
    expect(rows).toHaveLength(1);
    expect(rows[0]?.id).toBe(created.id);
  });
});
