/**
 * admin-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { schema as tenantsModule } from "../modules/tenants/schema.js";
import { schema as configModule } from "../modules/config/schema.js";
import { schema as healthModule } from "../modules/health/schema.js";
import { schema as backupModule } from "../modules/backup/schema.js";
import { schema as supportModule } from "../modules/support/schema.js";
import { schema as apiKeysModule } from "../modules/api-keys/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...tenantsModule,
  ...configModule,
  ...healthModule,
  ...backupModule,
  ...supportModule,
  ...apiKeysModule,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
