/**
 * court-service DB connection — TenantRouter adoption (Req 1.1, 1.7).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 *
 * All tables live in the `court` PostgreSQL schema (see modules/{module}/schema.ts,
 * which build on `pgSchema("court")`).
 */
import { createTenantDb } from "@civitasone/db";
import { caseRegistrySchema } from "../modules/case-registry/schema.js";
import { courtRegistrySchema } from "../modules/court-registry/schema.js";
import { hearingSchema } from "../modules/hearing/schema.js";
import { filingSchema } from "../modules/filing/schema.js";
import { orderSchema } from "../modules/order/schema.js";
import { causeListSchema } from "../modules/cause-list/schema.js";
import { scrutinySchema } from "../modules/scrutiny/schema.js";
import { noticeSchema } from "../modules/notice/schema.js";
import { complianceSchema } from "../modules/compliance/schema.js";
import { appealSchema } from "../modules/appeal/schema.js";
import { evidenceSchema } from "../modules/evidence/schema.js";
import { configSchema } from "../modules/config-registry/schema.js";
import { certifiedCopySchema } from "../modules/certified-copy/schema.js";
import { parcelSchema } from "../modules/case-parcel/schema.js";
import { publicLookupSchema } from "../modules/public-lookup/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...caseRegistrySchema,
  ...courtRegistrySchema,
  ...hearingSchema,
  ...filingSchema,
  ...orderSchema,
  ...causeListSchema,
  ...scrutinySchema,
  ...noticeSchema,
  ...complianceSchema,
  ...appealSchema,
  ...evidenceSchema,
  ...configSchema,
  ...certifiedCopySchema,
  ...parcelSchema,
  ...publicLookupSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes
 * `createTenantDb`'s `wrapWithTenantGuc`-wrapped `db` set the GUC from
 * AsyncLocalStorage — reads are then correctly tenant-scoped by RLS, not
 * merely by an app-layer WHERE. Preserved verbatim across the
 * TenantRouter-adoption codemod so every existing `repo.ts` call site
 * continues to import the same `scopedRead` helper unchanged.
 */
export function scopedRead<T>(fn: (tx: any) => Promise<T>): Promise<T> {
  return db.transaction(fn);
}
