/** Topic + event names owned by ai-agent-service. {service}.{entity}.{action} */
export const COMMANDS = {
  sendMessage: "ai.chat.send",
  endConversation: "ai.chat.end",
  recordBlockedAudit: "ai.audit.blocked",
  askCopilot: "ai.copilot.ask",
  summarize: "ai.copilot.summarize",
  invokeAgent: "ai.agent.invoke",
  createAgent: "ai.agent.create",
  updateAgent: "ai.agent.update",
  deleteAgent: "ai.agent.delete",
  pauseAgent: "ai.agent.pause",
  resumeAgent: "ai.agent.resume",
  handoffAgent: "ai.agent.handoff",
  checkGuardrails: "ai.guardrails.check",
  checkInjection: "ai.guardrails.check_injection",
  createGuardrailRule: "ai.guardrails.rule_create",
  updateGuardrailRule: "ai.guardrails.rule_update",
  deleteGuardrailRule: "ai.guardrails.rule_delete",
  startOrchestration: "ai.orchestration.start",
  recordHandoff: "ai.orchestration.handoff",
  abortOrchestration: "ai.orchestration.abort",
  draftAgentDefinition: "ai.authoring.draft",
  updateAgentDefinition: "ai.authoring.update",
  publishAgentDefinition: "ai.authoring.publish",
  archiveAgentDefinition: "ai.authoring.archive",
  scoreInteraction: "ai.quality.score",
  startChatSession: "ai.chat.session_start",
  suggest: "ai.copilot.suggest",
  recordReactStep: "ai.agent.react_step",
  registerProtocol: "ai.protocol.register",
  updateProtocol: "ai.protocol.update",
  defineTool: "ai.tool.define",
  updateTool: "ai.tool.update",
  seedDefaultTools: "ai.tool.seed_defaults",
} as const;

export const EVENTS = {
  conversationStarted: "ai.conversation.started",
  turnCompleted: "ai.turn.completed",
  handoffTriggered: "ai.agent.handoff_triggered",
  agentPaused: "ai.agent.paused",
  orchestrationStarted: "ai.orchestration.started",
  orchestrationHopRecorded: "ai.orchestration.hop_recorded",
  orchestrationLimitExceeded: "ai.orchestration.limit_exceeded",
  orchestrationAborted: "ai.orchestration.aborted",
  agentDefinitionDrafted: "ai.authoring.drafted",
  agentDefinitionPublished: "ai.authoring.published",
  agentDefinitionArchived: "ai.authoring.archived",
  interactionScored: "ai.quality.scored",
  interactionFlagged: "ai.quality.flagged",
  protocolRegistered: "ai.protocol.registered",
  protocolUpdated: "ai.protocol.updated",
  toolDefined: "ai.tool.defined",
  toolUpdated: "ai.tool.updated",
  reactStepRecorded: "ai.agent.react_step_recorded",
  reactStepPendingApproval: "ai.agent.react_step_pending_approval",
  injectionDetected: "ai.guardrails.injection_detected",
} as const;

export const INBOUND = {} as const;
export const AUDIT_TOPIC = "audit.event.record";
export const SERVICE = "ai-agent";
