/**
 * notification-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { templatesModuleSchema } from "../modules/templates/schema.js";
import { deliveriesModuleSchema } from "../modules/deliveries/schema.js";
import { channelsModuleSchema } from "../modules/channels/schema.js";
import { alertsModuleSchema } from "../modules/alerts/schema.js";
import { bulkModuleSchema } from "../modules/bulk/schema.js";
import { streamModuleSchema } from "../modules/stream/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...templatesModuleSchema,
  ...deliveriesModuleSchema,
  ...channelsModuleSchema,
  ...alertsModuleSchema,
  ...bulkModuleSchema,
  ...streamModuleSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
