/**
 * notification-service DB connection — TenantRouter adoption (Req 1.1).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 */
import { createTenantDb } from "@civitasone/db";
import { templatesModuleSchema } from "../modules/templates/schema.js";
import { deliveriesModuleSchema } from "../modules/deliveries/schema.js";
import { channelsModuleSchema } from "../modules/channels/schema.js";
import { alertsModuleSchema } from "../modules/alerts/schema.js";
import { bulkModuleSchema } from "../modules/bulk/schema.js";
import { streamModuleSchema } from "../modules/stream/schema.js";
import { schedulingModuleSchema } from "../modules/scheduling/schema.js";
import { digestModuleSchema } from "../modules/digest/schema.js";
import { webhookModuleSchema } from "../modules/webhook/schema.js";
import { analyticsModuleSchema } from "../modules/analytics/schema.js";
import { dndModuleSchema } from "../modules/dnd/schema.js";
import { i18nModuleSchema } from "../modules/i18n/schema.js";
import { segmentsModuleSchema } from "../modules/segments/schema.js";
import { outboxSchema } from "./outbox.js";

const SCHEMA = {
  ...templatesModuleSchema,
  ...deliveriesModuleSchema,
  ...channelsModuleSchema,
  ...alertsModuleSchema,
  ...bulkModuleSchema,
  ...streamModuleSchema,
  ...schedulingModuleSchema,
  ...digestModuleSchema,
  ...webhookModuleSchema,
  ...analyticsModuleSchema,
  ...dndModuleSchema,
  ...i18nModuleSchema,
  ...segmentsModuleSchema,
  ...outboxSchema,
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;

/**
 * Run a READ inside the tenant transaction so PostgreSQL RLS is enforced on
 * the read path too. Plain `db.select()` runs on a pooled connection with no
 * `app.tenant_id` GUC set, so under a NOBYPASSRLS role the fail-closed policy
 * returns ZERO rows. Wrapping the read in `db.transaction` makes createTenantDb's
 * `wrapWithTenantGuc`-wrapped `db` set the GUC from AsyncLocalStorage -- reads
 * are then correctly tenant-scoped by RLS, not merely by an app-layer WHERE.
 */
type ScopedTx = Parameters<Parameters<Db["transaction"]>[0]>[0];
export function scopedRead<T>(fn: (tx: ScopedTx) => PromiseLike<T>): Promise<T> {
  // Runtime is identical to `db.transaction(fn)`; the typed `tx` param lets
  // drizzle row types flow back to callers with no per-callsite annotations.
  return db.transaction(fn as (tx: ScopedTx) => Promise<T>);
}
