/**
 * meeting-service DB connection — TenantRouter adoption (Req 1.1, 1.7).
 * @generated by scripts/codemod/adopt-tenant-router.mjs — do not edit manually.
 * Reviewed for correctness (schema wiring), not style, per this service's PR.
 * See packages/db/src/create-tenant-db.ts for the createTenantDb() contract.
 *
 * All tables live in the `meeting` PostgreSQL schema (see modules/{module}/schema.ts,
 * which build on `pgSchema("meeting")`). Module schemas are merged into the schema
 * map below as each module lands (meeting-core, committee, agenda, …).
 */
import { createTenantDb } from "@civitasone/db";

const SCHEMA = {
  // ...meetingCoreModule, ...committeeModule, ...agendaModule, (added per module task)
  // ...outboxSchema, (added in task 1.3)
};

const { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead } = createTenantDb({ schema: SCHEMA });

export { sqlClient, db, dbFor, sqlClientFor, tierOf, dbForRead };
export type Db = typeof db;
